packages:
  - packages/*

overrides:
  source-map-js: '>=1.2.2 <2'

#minimumReleaseAge: 10080

onlyBuiltDependencies:
  - '@openapitools/openapi-generator-cli'
  - esbuild

ignoredBuiltDependencies:
  - '@nestjs/core'

allowBuilds:
  '@nestjs/core': true
  '@openapitools/openapi-generator-cli': true
  esbuild: true
  vue-demi: true
