/* tslint:disable */
/* eslint-disable */
/**
 * TBA III
 * Diese API ermöglicht den Zugriff auf Auswertungsdaten von VERA. Sie bietet Endpunkte für die Abfrage von Leistungsdaten auf verschiedenen Ebenen (Lerngruppe, Schule, Bundesland) und für verschiedene Arten von Daten (Kompetenzstufen, Item-Statistiken, Aggregationen).
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime'
import type { AggregationsInner, CompetenceLevelsInner, ItemsInner } from '../models/index'
import {
    AggregationsInnerFromJSON,
    AggregationsInnerToJSON,
    CompetenceLevelsInnerFromJSON,
    CompetenceLevelsInnerToJSON,
    ItemsInnerFromJSON,
    ItemsInnerToJSON,
} from '../models/index'

export interface GetGroupAggregationsRequest {
    id: string
    type?: string
    aggregation?: string
    comparison?: string
}

export interface GetGroupCompetenceLevelsRequest {
    id: string
    type?: string
    comparison?: string
}

export interface GetGroupItemsRequest {
    id: string
    type?: string
    comparison?: string
}

/**
 *
 */
export class GroupsApi extends runtime.BaseAPI {
    /**
     * Creates request options for getGroupAggregations without sending the request
     */
    async getGroupAggregationsRequestOpts(requestParameters: GetGroupAggregationsRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError('id', 'Required parameter "id" was null or undefined when calling getGroupAggregations().')
        }

        const queryParameters: any = {}

        if (requestParameters['type'] != null) {
            queryParameters['type'] = requestParameters['type']
        }

        if (requestParameters['aggregation'] != null) {
            queryParameters['aggregation'] = requestParameters['aggregation']
        }

        if (requestParameters['comparison'] != null) {
            queryParameters['comparison'] = requestParameters['comparison']
        }

        const headerParameters: runtime.HTTPHeaders = {}

        let urlPath = `/groups/{id}/aggregations`
        urlPath = urlPath.replace(`{${'id'}}`, encodeURIComponent(String(requestParameters['id'])))

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }
    }

    /**
     * Aggregierte Werte (z.B. Lösungshäufigkeiten) in der Lerngruppe
     */
    async getGroupAggregationsRaw(
        requestParameters: GetGroupAggregationsRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<runtime.ApiResponse<Array<AggregationsInner>>> {
        const requestOptions = await this.getGroupAggregationsRequestOpts(requestParameters)
        const response = await this.request(requestOptions, initOverrides)

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(AggregationsInnerFromJSON))
    }

    /**
     * Aggregierte Werte (z.B. Lösungshäufigkeiten) in der Lerngruppe
     */
    async getGroupAggregations(
        requestParameters: GetGroupAggregationsRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<Array<AggregationsInner>> {
        const response = await this.getGroupAggregationsRaw(requestParameters, initOverrides)
        return await response.value()
    }

    /**
     * Creates request options for getGroupCompetenceLevels without sending the request
     */
    async getGroupCompetenceLevelsRequestOpts(requestParameters: GetGroupCompetenceLevelsRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError('id', 'Required parameter "id" was null or undefined when calling getGroupCompetenceLevels().')
        }

        const queryParameters: any = {}

        if (requestParameters['type'] != null) {
            queryParameters['type'] = requestParameters['type']
        }

        if (requestParameters['comparison'] != null) {
            queryParameters['comparison'] = requestParameters['comparison']
        }

        const headerParameters: runtime.HTTPHeaders = {}

        let urlPath = `/groups/{id}/competence-levels`
        urlPath = urlPath.replace(`{${'id'}}`, encodeURIComponent(String(requestParameters['id'])))

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }
    }

    /**
     * Kompetenzstufenverteilung in der Lerngruppe
     */
    async getGroupCompetenceLevelsRaw(
        requestParameters: GetGroupCompetenceLevelsRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<runtime.ApiResponse<Array<CompetenceLevelsInner>>> {
        const requestOptions = await this.getGroupCompetenceLevelsRequestOpts(requestParameters)
        const response = await this.request(requestOptions, initOverrides)

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(CompetenceLevelsInnerFromJSON))
    }

    /**
     * Kompetenzstufenverteilung in der Lerngruppe
     */
    async getGroupCompetenceLevels(
        requestParameters: GetGroupCompetenceLevelsRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<Array<CompetenceLevelsInner>> {
        const response = await this.getGroupCompetenceLevelsRaw(requestParameters, initOverrides)
        return await response.value()
    }

    /**
     * Creates request options for getGroupItems without sending the request
     */
    async getGroupItemsRequestOpts(requestParameters: GetGroupItemsRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError('id', 'Required parameter "id" was null or undefined when calling getGroupItems().')
        }

        const queryParameters: any = {}

        if (requestParameters['type'] != null) {
            queryParameters['type'] = requestParameters['type']
        }

        if (requestParameters['comparison'] != null) {
            queryParameters['comparison'] = requestParameters['comparison']
        }

        const headerParameters: runtime.HTTPHeaders = {}

        let urlPath = `/groups/{id}/items`
        urlPath = urlPath.replace(`{${'id'}}`, encodeURIComponent(String(requestParameters['id'])))

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }
    }

    /**
     * Lösungshäufigkeiten je Item in der Lerngruppe
     */
    async getGroupItemsRaw(
        requestParameters: GetGroupItemsRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<runtime.ApiResponse<Array<ItemsInner>>> {
        const requestOptions = await this.getGroupItemsRequestOpts(requestParameters)
        const response = await this.request(requestOptions, initOverrides)

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(ItemsInnerFromJSON))
    }

    /**
     * Lösungshäufigkeiten je Item in der Lerngruppe
     */
    async getGroupItems(
        requestParameters: GetGroupItemsRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<Array<ItemsInner>> {
        const response = await this.getGroupItemsRaw(requestParameters, initOverrides)
        return await response.value()
    }
}
