/* tslint:disable */
/* eslint-disable */
/**
 * TBA III
 * Diese API ermöglicht den Zugriff auf Auswertungsdaten von VERA. Sie bietet Endpunkte für die Abfrage von Leistungsdaten auf verschiedenen Ebenen (Lerngruppe, Schule, Bundesland) und für verschiedene Arten von Daten (Kompetenzstufen, Item-Statistiken, Aggregationen).
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime'
import type { AggregationsInner, CompetenceLevelsInner, ItemsInner } from '../models/index'
import {
    AggregationsInnerFromJSON,
    AggregationsInnerToJSON,
    CompetenceLevelsInnerFromJSON,
    CompetenceLevelsInnerToJSON,
    ItemsInnerFromJSON,
    ItemsInnerToJSON,
} from '../models/index'

export interface GetSchoolAggregationsRequest {
    id: string
    type?: string
    aggregation?: string
    comparison?: string
}

export interface GetSchoolCompetenceLevelsRequest {
    id: string
    comparison?: string
}

export interface GetSchoolItemsRequest {
    id: string
    comparison?: string
}

/**
 *
 */
export class SchoolsApi extends runtime.BaseAPI {
    /**
     * Creates request options for getSchoolAggregations without sending the request
     */
    async getSchoolAggregationsRequestOpts(requestParameters: GetSchoolAggregationsRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError('id', 'Required parameter "id" was null or undefined when calling getSchoolAggregations().')
        }

        const queryParameters: any = {}

        if (requestParameters['type'] != null) {
            queryParameters['type'] = requestParameters['type']
        }

        if (requestParameters['aggregation'] != null) {
            queryParameters['aggregation'] = requestParameters['aggregation']
        }

        if (requestParameters['comparison'] != null) {
            queryParameters['comparison'] = requestParameters['comparison']
        }

        const headerParameters: runtime.HTTPHeaders = {}

        let urlPath = `/schools/{id}/aggregations`
        urlPath = urlPath.replace(`{${'id'}}`, encodeURIComponent(String(requestParameters['id'])))

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }
    }

    /**
     * Aggregierte Werte (z.B. Lösungshäufigkeiten) an der Schule
     */
    async getSchoolAggregationsRaw(
        requestParameters: GetSchoolAggregationsRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<runtime.ApiResponse<Array<AggregationsInner>>> {
        const requestOptions = await this.getSchoolAggregationsRequestOpts(requestParameters)
        const response = await this.request(requestOptions, initOverrides)

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(AggregationsInnerFromJSON))
    }

    /**
     * Aggregierte Werte (z.B. Lösungshäufigkeiten) an der Schule
     */
    async getSchoolAggregations(
        requestParameters: GetSchoolAggregationsRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<Array<AggregationsInner>> {
        const response = await this.getSchoolAggregationsRaw(requestParameters, initOverrides)
        return await response.value()
    }

    /**
     * Creates request options for getSchoolCompetenceLevels without sending the request
     */
    async getSchoolCompetenceLevelsRequestOpts(requestParameters: GetSchoolCompetenceLevelsRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError('id', 'Required parameter "id" was null or undefined when calling getSchoolCompetenceLevels().')
        }

        const queryParameters: any = {}

        if (requestParameters['comparison'] != null) {
            queryParameters['comparison'] = requestParameters['comparison']
        }

        const headerParameters: runtime.HTTPHeaders = {}

        let urlPath = `/schools/{id}/competence-levels`
        urlPath = urlPath.replace(`{${'id'}}`, encodeURIComponent(String(requestParameters['id'])))

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }
    }

    /**
     * Kompetenzstufenverteilung an der Schule
     */
    async getSchoolCompetenceLevelsRaw(
        requestParameters: GetSchoolCompetenceLevelsRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<runtime.ApiResponse<Array<CompetenceLevelsInner>>> {
        const requestOptions = await this.getSchoolCompetenceLevelsRequestOpts(requestParameters)
        const response = await this.request(requestOptions, initOverrides)

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(CompetenceLevelsInnerFromJSON))
    }

    /**
     * Kompetenzstufenverteilung an der Schule
     */
    async getSchoolCompetenceLevels(
        requestParameters: GetSchoolCompetenceLevelsRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<Array<CompetenceLevelsInner>> {
        const response = await this.getSchoolCompetenceLevelsRaw(requestParameters, initOverrides)
        return await response.value()
    }

    /**
     * Creates request options for getSchoolItems without sending the request
     */
    async getSchoolItemsRequestOpts(requestParameters: GetSchoolItemsRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError('id', 'Required parameter "id" was null or undefined when calling getSchoolItems().')
        }

        const queryParameters: any = {}

        if (requestParameters['comparison'] != null) {
            queryParameters['comparison'] = requestParameters['comparison']
        }

        const headerParameters: runtime.HTTPHeaders = {}

        let urlPath = `/schools/{id}/items`
        urlPath = urlPath.replace(`{${'id'}}`, encodeURIComponent(String(requestParameters['id'])))

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }
    }

    /**
     * Lösungshäufigkeiten je Item an der Schule
     */
    async getSchoolItemsRaw(
        requestParameters: GetSchoolItemsRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<runtime.ApiResponse<Array<ItemsInner>>> {
        const requestOptions = await this.getSchoolItemsRequestOpts(requestParameters)
        const response = await this.request(requestOptions, initOverrides)

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(ItemsInnerFromJSON))
    }

    /**
     * Lösungshäufigkeiten je Item an der Schule
     */
    async getSchoolItems(
        requestParameters: GetSchoolItemsRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<Array<ItemsInner>> {
        const response = await this.getSchoolItemsRaw(requestParameters, initOverrides)
        return await response.value()
    }
}
