/* tslint:disable */
/* eslint-disable */
/**
 * TBA III
 * Diese API ermöglicht den Zugriff auf Auswertungsdaten von VERA. Sie bietet Endpunkte für die Abfrage von Leistungsdaten auf verschiedenen Ebenen (Lerngruppe, Schule, Bundesland) und für verschiedene Arten von Daten (Kompetenzstufen, Item-Statistiken, Aggregationen).
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime'
import type { AggregationsInner, CompetenceLevelsInner, ItemsInner } from '../models/index'
import {
    AggregationsInnerFromJSON,
    AggregationsInnerToJSON,
    CompetenceLevelsInnerFromJSON,
    CompetenceLevelsInnerToJSON,
    ItemsInnerFromJSON,
    ItemsInnerToJSON,
} from '../models/index'

export interface GetStateAggregationsRequest {
    id: string
    type?: string
    aggregation?: string
    comparison?: string
}

export interface GetStateCompetenceLevelsRequest {
    id: string
    comparison?: string
}

export interface GetStateItemsRequest {
    id: string
    comparison?: string
}

/**
 *
 */
export class StatesApi extends runtime.BaseAPI {
    /**
     * Creates request options for getStateAggregations without sending the request
     */
    async getStateAggregationsRequestOpts(requestParameters: GetStateAggregationsRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError('id', 'Required parameter "id" was null or undefined when calling getStateAggregations().')
        }

        const queryParameters: any = {}

        if (requestParameters['type'] != null) {
            queryParameters['type'] = requestParameters['type']
        }

        if (requestParameters['aggregation'] != null) {
            queryParameters['aggregation'] = requestParameters['aggregation']
        }

        if (requestParameters['comparison'] != null) {
            queryParameters['comparison'] = requestParameters['comparison']
        }

        const headerParameters: runtime.HTTPHeaders = {}

        let urlPath = `/states/{id}/aggregations`
        urlPath = urlPath.replace(`{${'id'}}`, encodeURIComponent(String(requestParameters['id'])))

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }
    }

    /**
     * Aggregierte Werte (z.B. Lösungshäufigkeiten) im Bundesland
     */
    async getStateAggregationsRaw(
        requestParameters: GetStateAggregationsRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<runtime.ApiResponse<Array<AggregationsInner>>> {
        const requestOptions = await this.getStateAggregationsRequestOpts(requestParameters)
        const response = await this.request(requestOptions, initOverrides)

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(AggregationsInnerFromJSON))
    }

    /**
     * Aggregierte Werte (z.B. Lösungshäufigkeiten) im Bundesland
     */
    async getStateAggregations(
        requestParameters: GetStateAggregationsRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<Array<AggregationsInner>> {
        const response = await this.getStateAggregationsRaw(requestParameters, initOverrides)
        return await response.value()
    }

    /**
     * Creates request options for getStateCompetenceLevels without sending the request
     */
    async getStateCompetenceLevelsRequestOpts(requestParameters: GetStateCompetenceLevelsRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError('id', 'Required parameter "id" was null or undefined when calling getStateCompetenceLevels().')
        }

        const queryParameters: any = {}

        if (requestParameters['comparison'] != null) {
            queryParameters['comparison'] = requestParameters['comparison']
        }

        const headerParameters: runtime.HTTPHeaders = {}

        let urlPath = `/states/{id}/competence-levels`
        urlPath = urlPath.replace(`{${'id'}}`, encodeURIComponent(String(requestParameters['id'])))

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }
    }

    /**
     * Kompetenzstufenverteilung im Bundesland
     */
    async getStateCompetenceLevelsRaw(
        requestParameters: GetStateCompetenceLevelsRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<runtime.ApiResponse<Array<CompetenceLevelsInner>>> {
        const requestOptions = await this.getStateCompetenceLevelsRequestOpts(requestParameters)
        const response = await this.request(requestOptions, initOverrides)

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(CompetenceLevelsInnerFromJSON))
    }

    /**
     * Kompetenzstufenverteilung im Bundesland
     */
    async getStateCompetenceLevels(
        requestParameters: GetStateCompetenceLevelsRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<Array<CompetenceLevelsInner>> {
        const response = await this.getStateCompetenceLevelsRaw(requestParameters, initOverrides)
        return await response.value()
    }

    /**
     * Creates request options for getStateItems without sending the request
     */
    async getStateItemsRequestOpts(requestParameters: GetStateItemsRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError('id', 'Required parameter "id" was null or undefined when calling getStateItems().')
        }

        const queryParameters: any = {}

        if (requestParameters['comparison'] != null) {
            queryParameters['comparison'] = requestParameters['comparison']
        }

        const headerParameters: runtime.HTTPHeaders = {}

        let urlPath = `/states/{id}/items`
        urlPath = urlPath.replace(`{${'id'}}`, encodeURIComponent(String(requestParameters['id'])))

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }
    }

    /**
     * Lösungshäufigkeiten je Item im Bundesland
     */
    async getStateItemsRaw(
        requestParameters: GetStateItemsRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<runtime.ApiResponse<Array<ItemsInner>>> {
        const requestOptions = await this.getStateItemsRequestOpts(requestParameters)
        const response = await this.request(requestOptions, initOverrides)

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(ItemsInnerFromJSON))
    }

    /**
     * Lösungshäufigkeiten je Item im Bundesland
     */
    async getStateItems(
        requestParameters: GetStateItemsRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<Array<ItemsInner>> {
        const response = await this.getStateItemsRaw(requestParameters, initOverrides)
        return await response.value()
    }
}
