/* tslint:disable */
/* eslint-disable */
/**
 * Auth
 * Authentifizierungs-Endpunkte fuer api.inio.de/auth. Die Spezifikation bildet den bestehenden Auth-Flow mit API-Keys, Session-Token und Bearer-JWT ab.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime'
import type {
    CheckGet200Response,
    ErrorResponse,
    GenerateJwtDataResponse,
    JwtTokenSchoolResponse,
    JwtTokenUserResponse,
    SchoolLoginRequest,
    StudentLoginRequest,
} from '../models/index'
import {
    CheckGet200ResponseFromJSON,
    CheckGet200ResponseToJSON,
    ErrorResponseFromJSON,
    ErrorResponseToJSON,
    GenerateJwtDataResponseFromJSON,
    GenerateJwtDataResponseToJSON,
    JwtTokenSchoolResponseFromJSON,
    JwtTokenSchoolResponseToJSON,
    JwtTokenUserResponseFromJSON,
    JwtTokenUserResponseToJSON,
    SchoolLoginRequestFromJSON,
    SchoolLoginRequestToJSON,
    StudentLoginRequestFromJSON,
    StudentLoginRequestToJSON,
} from '../models/index'

export interface GenerateJwtGetRequest {
    schoolId: number
    service: GenerateJwtGetServiceEnum
    expiresDays: number
}

export interface SchoolPostRequest {
    schoolLoginRequest: SchoolLoginRequest
}

export interface StudentPostRequest {
    studentLoginRequest: StudentLoginRequest
}

/**
 *
 */
export class AuthApi extends runtime.BaseAPI {
    /**
     * Creates request options for checkGet without sending the request
     */
    async checkGetRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {}

        const headerParameters: runtime.HTTPHeaders = {}

        if (this.configuration && this.configuration.apiKey) {
            headerParameters['X-API-KEY-SCHOOL'] = await this.configuration.apiKey('X-API-KEY-SCHOOL') // X-API-KEY-SCHOOL authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters['X-API-KEY'] = await this.configuration.apiKey('X-API-KEY') // X-API-KEY authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters['X-API-KEY-USER'] = await this.configuration.apiKey('X-API-KEY-USER') // X-API-KEY-USER authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken
            const tokenString = await token('BearerAuth', [])

            if (tokenString) {
                headerParameters['Authorization'] = `Bearer ${tokenString}`
            }
        }

        let urlPath = `/check`

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }
    }

    /**
     * Prueft die uebergebenen Zugangsdaten und liefert die authentifizierten User- oder Schulinformationen zurueck.
     * Authentifizierungsstatus abrufen
     */
    async checkGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CheckGet200Response>> {
        const requestOptions = await this.checkGetRequestOpts()
        const response = await this.request(requestOptions, initOverrides)

        return new runtime.JSONApiResponse(response, (jsonValue) => CheckGet200ResponseFromJSON(jsonValue))
    }

    /**
     * Prueft die uebergebenen Zugangsdaten und liefert die authentifizierten User- oder Schulinformationen zurueck.
     * Authentifizierungsstatus abrufen
     */
    async checkGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CheckGet200Response> {
        const response = await this.checkGetRaw(initOverrides)
        return await response.value()
    }

    /**
     * Creates request options for generateJwtGet without sending the request
     */
    async generateJwtGetRequestOpts(requestParameters: GenerateJwtGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['schoolId'] == null) {
            throw new runtime.RequiredError(
                'schoolId',
                'Required parameter "schoolId" was null or undefined when calling generateJwtGet().',
            )
        }

        if (requestParameters['service'] == null) {
            throw new runtime.RequiredError('service', 'Required parameter "service" was null or undefined when calling generateJwtGet().')
        }

        if (requestParameters['expiresDays'] == null) {
            throw new runtime.RequiredError(
                'expiresDays',
                'Required parameter "expiresDays" was null or undefined when calling generateJwtGet().',
            )
        }

        const queryParameters: any = {}

        if (requestParameters['schoolId'] != null) {
            queryParameters['schoolId'] = requestParameters['schoolId']
        }

        if (requestParameters['service'] != null) {
            queryParameters['service'] = requestParameters['service']
        }

        if (requestParameters['expiresDays'] != null) {
            queryParameters['expiresDays'] = requestParameters['expiresDays']
        }

        const headerParameters: runtime.HTTPHeaders = {}

        if (this.configuration && this.configuration.apiKey) {
            headerParameters['X-API-KEY-USER'] = await this.configuration.apiKey('X-API-KEY-USER') // X-API-KEY-USER authentication
        }

        let urlPath = `/generate-jwt`

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }
    }

    /**
     * Erzeugt ein Bearer-JWT fuer eine Schule anhand von schoolId, service und expiresDays. Dieser Endpunkt ist nur fuer authentifizierte KT-User vorgesehen.
     * JWT fuer Schule erzeugen
     */
    async generateJwtGetRaw(
        requestParameters: GenerateJwtGetRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<runtime.ApiResponse<GenerateJwtDataResponse>> {
        const requestOptions = await this.generateJwtGetRequestOpts(requestParameters)
        const response = await this.request(requestOptions, initOverrides)

        return new runtime.JSONApiResponse(response, (jsonValue) => GenerateJwtDataResponseFromJSON(jsonValue))
    }

    /**
     * Erzeugt ein Bearer-JWT fuer eine Schule anhand von schoolId, service und expiresDays. Dieser Endpunkt ist nur fuer authentifizierte KT-User vorgesehen.
     * JWT fuer Schule erzeugen
     */
    async generateJwtGet(
        requestParameters: GenerateJwtGetRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<GenerateJwtDataResponse> {
        const response = await this.generateJwtGetRaw(requestParameters, initOverrides)
        return await response.value()
    }

    /**
     * Creates request options for schoolPost without sending the request
     */
    async schoolPostRequestOpts(requestParameters: SchoolPostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['schoolLoginRequest'] == null) {
            throw new runtime.RequiredError(
                'schoolLoginRequest',
                'Required parameter "schoolLoginRequest" was null or undefined when calling schoolPost().',
            )
        }

        const queryParameters: any = {}

        const headerParameters: runtime.HTTPHeaders = {}

        headerParameters['Content-Type'] = 'application/json'

        if (this.configuration && this.configuration.apiKey) {
            headerParameters['X-API-KEY-SCHOOL'] = await this.configuration.apiKey('X-API-KEY-SCHOOL') // X-API-KEY-SCHOOL authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters['X-API-KEY'] = await this.configuration.apiKey('X-API-KEY') // X-API-KEY authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters['X-API-KEY-USER'] = await this.configuration.apiKey('X-API-KEY-USER') // X-API-KEY-USER authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken
            const tokenString = await token('BearerAuth', [])

            if (tokenString) {
                headerParameters['Authorization'] = `Bearer ${tokenString}`
            }
        }

        let urlPath = `/school`

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: SchoolLoginRequestToJSON(requestParameters['schoolLoginRequest']),
        }
    }

    /**
     * Authentifiziert eine Schule ueber bundesland, schulname und passwort. Bei gueltigen Zugangsdaten wird ein Bearer-JWT zurueckgegeben.
     * Schule anmelden
     */
    async schoolPostRaw(
        requestParameters: SchoolPostRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<runtime.ApiResponse<JwtTokenSchoolResponse>> {
        const requestOptions = await this.schoolPostRequestOpts(requestParameters)
        const response = await this.request(requestOptions, initOverrides)

        return new runtime.JSONApiResponse(response, (jsonValue) => JwtTokenSchoolResponseFromJSON(jsonValue))
    }

    /**
     * Authentifiziert eine Schule ueber bundesland, schulname und passwort. Bei gueltigen Zugangsdaten wird ein Bearer-JWT zurueckgegeben.
     * Schule anmelden
     */
    async schoolPost(
        requestParameters: SchoolPostRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<JwtTokenSchoolResponse> {
        const response = await this.schoolPostRaw(requestParameters, initOverrides)
        return await response.value()
    }

    /**
     * Creates request options for studentPost without sending the request
     */
    async studentPostRequestOpts(requestParameters: StudentPostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['studentLoginRequest'] == null) {
            throw new runtime.RequiredError(
                'studentLoginRequest',
                'Required parameter "studentLoginRequest" was null or undefined when calling studentPost().',
            )
        }

        const queryParameters: any = {}

        const headerParameters: runtime.HTTPHeaders = {}

        headerParameters['Content-Type'] = 'application/json'

        if (this.configuration && this.configuration.apiKey) {
            headerParameters['X-API-KEY-SCHOOL'] = await this.configuration.apiKey('X-API-KEY-SCHOOL') // X-API-KEY-SCHOOL authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters['X-API-KEY'] = await this.configuration.apiKey('X-API-KEY') // X-API-KEY authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters['X-API-KEY-USER'] = await this.configuration.apiKey('X-API-KEY-USER') // X-API-KEY-USER authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken
            const tokenString = await token('BearerAuth', [])

            if (tokenString) {
                headerParameters['Authorization'] = `Bearer ${tokenString}`
            }
        }

        let urlPath = `/student`

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: StudentLoginRequestToJSON(requestParameters['studentLoginRequest']),
        }
    }

    /**
     * Authentifiziert einen Schueler ueber surveyId, Klassenpasswort und Login-Code. Bei gueltigen Zugangsdaten wird ein Bearer-JWT zurueckgegeben.
     * Schüler*in anmelden
     */
    async studentPostRaw(
        requestParameters: StudentPostRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<runtime.ApiResponse<JwtTokenUserResponse>> {
        const requestOptions = await this.studentPostRequestOpts(requestParameters)
        const response = await this.request(requestOptions, initOverrides)

        return new runtime.JSONApiResponse(response, (jsonValue) => JwtTokenUserResponseFromJSON(jsonValue))
    }

    /**
     * Authentifiziert einen Schueler ueber surveyId, Klassenpasswort und Login-Code. Bei gueltigen Zugangsdaten wird ein Bearer-JWT zurueckgegeben.
     * Schüler*in anmelden
     */
    async studentPost(
        requestParameters: StudentPostRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<JwtTokenUserResponse> {
        const response = await this.studentPostRaw(requestParameters, initOverrides)
        return await response.value()
    }
}

/**
 * @export
 */
export const GenerateJwtGetServiceEnum = {
    All: 'all',
    ReportData: 'report_data',
} as const
export type GenerateJwtGetServiceEnum = (typeof GenerateJwtGetServiceEnum)[keyof typeof GenerateJwtGetServiceEnum]
