/* tslint:disable */
/* eslint-disable */
/**
 * Auth
 * Authentifizierungs-Endpunkte fuer api.inio.de/auth. Die Spezifikation bildet den bestehenden Auth-Flow mit API-Keys, Session-Token und Bearer-JWT ab.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime'
import type { AuthSchoolInfoData } from './AuthSchoolInfoData'
import {
    AuthSchoolInfoDataFromJSON,
    AuthSchoolInfoDataFromJSONTyped,
    AuthSchoolInfoDataToJSON,
    AuthSchoolInfoDataToJSONTyped,
} from './AuthSchoolInfoData'

/**
 *
 * @export
 * @interface AuthSchoolInfoResponse
 */
export interface AuthSchoolInfoResponse {
    /**
     *
     * @type {boolean}
     * @memberof AuthSchoolInfoResponse
     */
    success: boolean
    /**
     *
     * @type {string}
     * @memberof AuthSchoolInfoResponse
     */
    message: string
    /**
     *
     * @type {AuthSchoolInfoData}
     * @memberof AuthSchoolInfoResponse
     */
    data?: AuthSchoolInfoData
}

/**
 * Check if a given object implements the AuthSchoolInfoResponse interface.
 */
export function instanceOfAuthSchoolInfoResponse(value: object): value is AuthSchoolInfoResponse {
    if (!('success' in value) || value['success'] === undefined) return false
    if (!('message' in value) || value['message'] === undefined) return false
    return true
}

export function AuthSchoolInfoResponseFromJSON(json: any): AuthSchoolInfoResponse {
    return AuthSchoolInfoResponseFromJSONTyped(json, false)
}

export function AuthSchoolInfoResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthSchoolInfoResponse {
    if (json == null) {
        return json
    }
    return {
        success: json['success'],
        message: json['message'],
        data: json['data'] == null ? undefined : AuthSchoolInfoDataFromJSON(json['data']),
    }
}

export function AuthSchoolInfoResponseToJSON(json: any): AuthSchoolInfoResponse {
    return AuthSchoolInfoResponseToJSONTyped(json, false)
}

export function AuthSchoolInfoResponseToJSONTyped(value?: AuthSchoolInfoResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value
    }

    return {
        success: value['success'],
        message: value['message'],
        data: AuthSchoolInfoDataToJSON(value['data']),
    }
}
