/* tslint:disable */
/* eslint-disable */
/**
 * Auth
 * Authentifizierungs-Endpunkte fuer api.inio.de/auth. Die Spezifikation bildet den bestehenden Auth-Flow mit API-Keys, Session-Token und Bearer-JWT ab.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime'
/**
 *
 * @export
 * @interface AuthUserInfoData
 */
export interface AuthUserInfoData {
    /**
     *
     * @type {number}
     * @memberof AuthUserInfoData
     */
    userId: number
    /**
     *
     * @type {string}
     * @memberof AuthUserInfoData
     */
    outname: string
}

/**
 * Check if a given object implements the AuthUserInfoData interface.
 */
export function instanceOfAuthUserInfoData(value: object): value is AuthUserInfoData {
    if (!('userId' in value) || value['userId'] === undefined) return false
    if (!('outname' in value) || value['outname'] === undefined) return false
    return true
}

export function AuthUserInfoDataFromJSON(json: any): AuthUserInfoData {
    return AuthUserInfoDataFromJSONTyped(json, false)
}

export function AuthUserInfoDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthUserInfoData {
    if (json == null) {
        return json
    }
    return {
        userId: json['userId'],
        outname: json['outname'],
    }
}

export function AuthUserInfoDataToJSON(json: any): AuthUserInfoData {
    return AuthUserInfoDataToJSONTyped(json, false)
}

export function AuthUserInfoDataToJSONTyped(value?: AuthUserInfoData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value
    }

    return {
        userId: value['userId'],
        outname: value['outname'],
    }
}
