/* tslint:disable */
/* eslint-disable */
/**
 * Auth
 * Authentifizierungs-Endpunkte fuer api.inio.de/auth. Die Spezifikation bildet den bestehenden Auth-Flow mit API-Keys, Session-Token und Bearer-JWT ab.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime'
import type { AuthUserInfoData } from './AuthUserInfoData'
import {
    AuthUserInfoDataFromJSON,
    AuthUserInfoDataFromJSONTyped,
    AuthUserInfoDataToJSON,
    AuthUserInfoDataToJSONTyped,
} from './AuthUserInfoData'

/**
 *
 * @export
 * @interface AuthUserInfoResponse
 */
export interface AuthUserInfoResponse {
    /**
     *
     * @type {boolean}
     * @memberof AuthUserInfoResponse
     */
    success: boolean
    /**
     *
     * @type {string}
     * @memberof AuthUserInfoResponse
     */
    message: string
    /**
     *
     * @type {AuthUserInfoData}
     * @memberof AuthUserInfoResponse
     */
    data?: AuthUserInfoData
}

/**
 * Check if a given object implements the AuthUserInfoResponse interface.
 */
export function instanceOfAuthUserInfoResponse(value: object): value is AuthUserInfoResponse {
    if (!('success' in value) || value['success'] === undefined) return false
    if (!('message' in value) || value['message'] === undefined) return false
    return true
}

export function AuthUserInfoResponseFromJSON(json: any): AuthUserInfoResponse {
    return AuthUserInfoResponseFromJSONTyped(json, false)
}

export function AuthUserInfoResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthUserInfoResponse {
    if (json == null) {
        return json
    }
    return {
        success: json['success'],
        message: json['message'],
        data: json['data'] == null ? undefined : AuthUserInfoDataFromJSON(json['data']),
    }
}

export function AuthUserInfoResponseToJSON(json: any): AuthUserInfoResponse {
    return AuthUserInfoResponseToJSONTyped(json, false)
}

export function AuthUserInfoResponseToJSONTyped(value?: AuthUserInfoResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value
    }

    return {
        success: value['success'],
        message: value['message'],
        data: AuthUserInfoDataToJSON(value['data']),
    }
}
