/* tslint:disable */
/* eslint-disable */
/**
 * Auth
 * Authentifizierungs-Endpunkte fuer api.inio.de/auth. Die Spezifikation bildet den bestehenden Auth-Flow mit API-Keys, Session-Token und Bearer-JWT ab.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime'
/**
 * Bereinigte Schulinformationen.
 * @export
 * @interface AuthSchoolInfoData
 */
export interface AuthSchoolInfoData {
    [key: string]: any | any
    /**
     *
     * @type {number}
     * @memberof AuthSchoolInfoData
     */
    id: number
    /**
     *
     * @type {string}
     * @memberof AuthSchoolInfoData
     */
    nr: string
    /**
     *
     * @type {string}
     * @memberof AuthSchoolInfoData
     */
    name: string
    /**
     *
     * @type {number}
     * @memberof AuthSchoolInfoData
     */
    region: number
}

/**
 * Check if a given object implements the AuthSchoolInfoData interface.
 */
export function instanceOfAuthSchoolInfoData(value: object): value is AuthSchoolInfoData {
    if (!('id' in value) || value['id'] === undefined) return false
    if (!('nr' in value) || value['nr'] === undefined) return false
    if (!('name' in value) || value['name'] === undefined) return false
    if (!('region' in value) || value['region'] === undefined) return false
    return true
}

export function AuthSchoolInfoDataFromJSON(json: any): AuthSchoolInfoData {
    return AuthSchoolInfoDataFromJSONTyped(json, false)
}

export function AuthSchoolInfoDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthSchoolInfoData {
    if (json == null) {
        return json
    }
    return {
        ...json,
        id: json['id'],
        nr: json['nr'],
        name: json['name'],
        region: json['region'],
    }
}

export function AuthSchoolInfoDataToJSON(json: any): AuthSchoolInfoData {
    return AuthSchoolInfoDataToJSONTyped(json, false)
}

export function AuthSchoolInfoDataToJSONTyped(value?: AuthSchoolInfoData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value
    }

    return {
        ...value,
        id: value['id'],
        nr: value['nr'],
        name: value['name'],
        region: value['region'],
    }
}
