/* tslint:disable */
/* eslint-disable */
/**
 * Auth
 * Authentifizierungs-Endpunkte fuer api.inio.de/auth. Die Spezifikation bildet den bestehenden Auth-Flow mit API-Keys, Session-Token und Bearer-JWT ab.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { AuthSchoolInfoResponse } from './AuthSchoolInfoResponse'
import {
    instanceOfAuthSchoolInfoResponse,
    AuthSchoolInfoResponseFromJSON,
    AuthSchoolInfoResponseFromJSONTyped,
    AuthSchoolInfoResponseToJSON,
} from './AuthSchoolInfoResponse'
import type { AuthUserInfoResponse } from './AuthUserInfoResponse'
import {
    instanceOfAuthUserInfoResponse,
    AuthUserInfoResponseFromJSON,
    AuthUserInfoResponseFromJSONTyped,
    AuthUserInfoResponseToJSON,
} from './AuthUserInfoResponse'

/**
 * @type CheckGet200Response
 *
 * @export
 */
export type CheckGet200Response = AuthSchoolInfoResponse | AuthUserInfoResponse

export function CheckGet200ResponseFromJSON(json: any): CheckGet200Response {
    return CheckGet200ResponseFromJSONTyped(json, false)
}

export function CheckGet200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CheckGet200Response {
    if (json == null) {
        return json
    }
    if (typeof json !== 'object') {
        return json
    }
    if (instanceOfAuthSchoolInfoResponse(json)) {
        return AuthSchoolInfoResponseFromJSONTyped(json, true)
    }
    if (instanceOfAuthUserInfoResponse(json)) {
        return AuthUserInfoResponseFromJSONTyped(json, true)
    }
    return {} as any
}

export function CheckGet200ResponseToJSON(json: any): any {
    return CheckGet200ResponseToJSONTyped(json, false)
}

export function CheckGet200ResponseToJSONTyped(value?: CheckGet200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value
    }
    if (typeof value !== 'object') {
        return value
    }
    if (instanceOfAuthSchoolInfoResponse(value)) {
        return AuthSchoolInfoResponseToJSON(value as AuthSchoolInfoResponse)
    }
    if (instanceOfAuthUserInfoResponse(value)) {
        return AuthUserInfoResponseToJSON(value as AuthUserInfoResponse)
    }
    return {}
}
