/* tslint:disable */
/* eslint-disable */
/**
 * Auth
 * Authentifizierungs-Endpunkte fuer api.inio.de/auth. Die Spezifikation bildet den bestehenden Auth-Flow mit API-Keys, Session-Token und Bearer-JWT ab.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime'
import type { JwtTokenData } from './JwtTokenData'
import { JwtTokenDataFromJSON, JwtTokenDataFromJSONTyped, JwtTokenDataToJSON, JwtTokenDataToJSONTyped } from './JwtTokenData'

/**
 *
 * @export
 * @interface GenerateJwtDataResponse
 */
export interface GenerateJwtDataResponse {
    /**
     *
     * @type {boolean}
     * @memberof GenerateJwtDataResponse
     */
    success: boolean
    /**
     *
     * @type {string}
     * @memberof GenerateJwtDataResponse
     */
    message: string
    /**
     *
     * @type {JwtTokenData}
     * @memberof GenerateJwtDataResponse
     */
    data?: JwtTokenData
}

/**
 * Check if a given object implements the GenerateJwtDataResponse interface.
 */
export function instanceOfGenerateJwtDataResponse(value: object): value is GenerateJwtDataResponse {
    if (!('success' in value) || value['success'] === undefined) return false
    if (!('message' in value) || value['message'] === undefined) return false
    return true
}

export function GenerateJwtDataResponseFromJSON(json: any): GenerateJwtDataResponse {
    return GenerateJwtDataResponseFromJSONTyped(json, false)
}

export function GenerateJwtDataResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GenerateJwtDataResponse {
    if (json == null) {
        return json
    }
    return {
        success: json['success'],
        message: json['message'],
        data: json['data'] == null ? undefined : JwtTokenDataFromJSON(json['data']),
    }
}

export function GenerateJwtDataResponseToJSON(json: any): GenerateJwtDataResponse {
    return GenerateJwtDataResponseToJSONTyped(json, false)
}

export function GenerateJwtDataResponseToJSONTyped(value?: GenerateJwtDataResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value
    }

    return {
        success: value['success'],
        message: value['message'],
        data: JwtTokenDataToJSON(value['data']),
    }
}
