/* tslint:disable */
/* eslint-disable */
export * from './AuthSchoolInfoData'
export * from './AuthSchoolInfoResponse'
export * from './AuthUserInfoData'
export * from './AuthUserInfoResponse'
export * from './CheckGet200Response'
export * from './ErrorResponse'
export * from './GenerateJwtDataResponse'
export * from './JwtTokenData'
export * from './JwtTokenSchoolResponse'
export * from './JwtTokenSchoolResponseAllOfData'
export * from './JwtTokenUserResponse'
export * from './JwtTokenUserResponseAllOfData'
export * from './SchoolLoginRequest'
export * from './StatusResponse'
export * from './StudentLoginRequest'
