/* tslint:disable */
/* eslint-disable */
/**
 * Auth
 * Authentifizierungs-Endpunkte fuer api.inio.de/auth. Die Spezifikation bildet den bestehenden Auth-Flow mit API-Keys, Session-Token und Bearer-JWT ab.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime'
import type { JwtTokenSchoolResponseAllOfData } from './JwtTokenSchoolResponseAllOfData'
import {
    JwtTokenSchoolResponseAllOfDataFromJSON,
    JwtTokenSchoolResponseAllOfDataFromJSONTyped,
    JwtTokenSchoolResponseAllOfDataToJSON,
    JwtTokenSchoolResponseAllOfDataToJSONTyped,
} from './JwtTokenSchoolResponseAllOfData'

/**
 *
 * @export
 * @interface JwtTokenSchoolResponse
 */
export interface JwtTokenSchoolResponse {
    /**
     *
     * @type {boolean}
     * @memberof JwtTokenSchoolResponse
     */
    success: boolean
    /**
     *
     * @type {string}
     * @memberof JwtTokenSchoolResponse
     */
    message: string
    /**
     *
     * @type {JwtTokenSchoolResponseAllOfData}
     * @memberof JwtTokenSchoolResponse
     */
    data?: JwtTokenSchoolResponseAllOfData
}

/**
 * Check if a given object implements the JwtTokenSchoolResponse interface.
 */
export function instanceOfJwtTokenSchoolResponse(value: object): value is JwtTokenSchoolResponse {
    if (!('success' in value) || value['success'] === undefined) return false
    if (!('message' in value) || value['message'] === undefined) return false
    return true
}

export function JwtTokenSchoolResponseFromJSON(json: any): JwtTokenSchoolResponse {
    return JwtTokenSchoolResponseFromJSONTyped(json, false)
}

export function JwtTokenSchoolResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): JwtTokenSchoolResponse {
    if (json == null) {
        return json
    }
    return {
        success: json['success'],
        message: json['message'],
        data: json['data'] == null ? undefined : JwtTokenSchoolResponseAllOfDataFromJSON(json['data']),
    }
}

export function JwtTokenSchoolResponseToJSON(json: any): JwtTokenSchoolResponse {
    return JwtTokenSchoolResponseToJSONTyped(json, false)
}

export function JwtTokenSchoolResponseToJSONTyped(value?: JwtTokenSchoolResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value
    }

    return {
        success: value['success'],
        message: value['message'],
        data: JwtTokenSchoolResponseAllOfDataToJSON(value['data']),
    }
}
