/* tslint:disable */
/* eslint-disable */
/**
 * Auth
 * Authentifizierungs-Endpunkte fuer api.inio.de/auth. Die Spezifikation bildet den bestehenden Auth-Flow mit API-Keys, Session-Token und Bearer-JWT ab.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime'
/**
 *
 * @export
 * @interface JwtTokenData
 */
export interface JwtTokenData {
    /**
     * JWT mit HS256 signiert
     * @type {string}
     * @memberof JwtTokenData
     */
    token: string
    /**
     *
     * @type {number}
     * @memberof JwtTokenData
     */
    tokenExpiresIn: number
}

/**
 * Check if a given object implements the JwtTokenData interface.
 */
export function instanceOfJwtTokenData(value: object): value is JwtTokenData {
    if (!('token' in value) || value['token'] === undefined) return false
    if (!('tokenExpiresIn' in value) || value['tokenExpiresIn'] === undefined) return false
    return true
}

export function JwtTokenDataFromJSON(json: any): JwtTokenData {
    return JwtTokenDataFromJSONTyped(json, false)
}

export function JwtTokenDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): JwtTokenData {
    if (json == null) {
        return json
    }
    return {
        token: json['token'],
        tokenExpiresIn: json['tokenExpiresIn'],
    }
}

export function JwtTokenDataToJSON(json: any): JwtTokenData {
    return JwtTokenDataToJSONTyped(json, false)
}

export function JwtTokenDataToJSONTyped(value?: JwtTokenData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value
    }

    return {
        token: value['token'],
        tokenExpiresIn: value['tokenExpiresIn'],
    }
}
