/* tslint:disable */
/* eslint-disable */
/**
 * Auth
 * Authentifizierungs-Endpunkte fuer api.inio.de/auth. Die Spezifikation bildet den bestehenden Auth-Flow mit API-Keys, Session-Token und Bearer-JWT ab.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime'
import type { JwtTokenUserResponseAllOfData } from './JwtTokenUserResponseAllOfData'
import {
    JwtTokenUserResponseAllOfDataFromJSON,
    JwtTokenUserResponseAllOfDataFromJSONTyped,
    JwtTokenUserResponseAllOfDataToJSON,
    JwtTokenUserResponseAllOfDataToJSONTyped,
} from './JwtTokenUserResponseAllOfData'

/**
 *
 * @export
 * @interface JwtTokenUserResponse
 */
export interface JwtTokenUserResponse {
    /**
     *
     * @type {boolean}
     * @memberof JwtTokenUserResponse
     */
    success: boolean
    /**
     *
     * @type {string}
     * @memberof JwtTokenUserResponse
     */
    message: string
    /**
     *
     * @type {JwtTokenUserResponseAllOfData}
     * @memberof JwtTokenUserResponse
     */
    data?: JwtTokenUserResponseAllOfData
}

/**
 * Check if a given object implements the JwtTokenUserResponse interface.
 */
export function instanceOfJwtTokenUserResponse(value: object): value is JwtTokenUserResponse {
    if (!('success' in value) || value['success'] === undefined) return false
    if (!('message' in value) || value['message'] === undefined) return false
    return true
}

export function JwtTokenUserResponseFromJSON(json: any): JwtTokenUserResponse {
    return JwtTokenUserResponseFromJSONTyped(json, false)
}

export function JwtTokenUserResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): JwtTokenUserResponse {
    if (json == null) {
        return json
    }
    return {
        success: json['success'],
        message: json['message'],
        data: json['data'] == null ? undefined : JwtTokenUserResponseAllOfDataFromJSON(json['data']),
    }
}

export function JwtTokenUserResponseToJSON(json: any): JwtTokenUserResponse {
    return JwtTokenUserResponseToJSONTyped(json, false)
}

export function JwtTokenUserResponseToJSONTyped(value?: JwtTokenUserResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value
    }

    return {
        success: value['success'],
        message: value['message'],
        data: JwtTokenUserResponseAllOfDataToJSON(value['data']),
    }
}
