/* tslint:disable */
/* eslint-disable */
/**
 * Auth
 * Authentifizierungs-Endpunkte fuer api.inio.de/auth. Die Spezifikation bildet den bestehenden Auth-Flow mit API-Keys, Session-Token und Bearer-JWT ab.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime'
/**
 *
 * @export
 * @interface JwtTokenSchoolResponseAllOfData
 */
export interface JwtTokenSchoolResponseAllOfData {
    /**
     * JWT mit HS256 signiert
     * @type {string}
     * @memberof JwtTokenSchoolResponseAllOfData
     */
    token: string
    /**
     *
     * @type {number}
     * @memberof JwtTokenSchoolResponseAllOfData
     */
    tokenExpiresIn: number
    /**
     *
     * @type {number}
     * @memberof JwtTokenSchoolResponseAllOfData
     */
    id: number
    /**
     *
     * @type {string}
     * @memberof JwtTokenSchoolResponseAllOfData
     */
    nr: string
    /**
     *
     * @type {string}
     * @memberof JwtTokenSchoolResponseAllOfData
     */
    name: string
    /**
     *
     * @type {number}
     * @memberof JwtTokenSchoolResponseAllOfData
     */
    region: number
}

/**
 * Check if a given object implements the JwtTokenSchoolResponseAllOfData interface.
 */
export function instanceOfJwtTokenSchoolResponseAllOfData(value: object): value is JwtTokenSchoolResponseAllOfData {
    if (!('token' in value) || value['token'] === undefined) return false
    if (!('tokenExpiresIn' in value) || value['tokenExpiresIn'] === undefined) return false
    if (!('id' in value) || value['id'] === undefined) return false
    if (!('nr' in value) || value['nr'] === undefined) return false
    if (!('name' in value) || value['name'] === undefined) return false
    if (!('region' in value) || value['region'] === undefined) return false
    return true
}

export function JwtTokenSchoolResponseAllOfDataFromJSON(json: any): JwtTokenSchoolResponseAllOfData {
    return JwtTokenSchoolResponseAllOfDataFromJSONTyped(json, false)
}

export function JwtTokenSchoolResponseAllOfDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): JwtTokenSchoolResponseAllOfData {
    if (json == null) {
        return json
    }
    return {
        token: json['token'],
        tokenExpiresIn: json['tokenExpiresIn'],
        id: json['id'],
        nr: json['nr'],
        name: json['name'],
        region: json['region'],
    }
}

export function JwtTokenSchoolResponseAllOfDataToJSON(json: any): JwtTokenSchoolResponseAllOfData {
    return JwtTokenSchoolResponseAllOfDataToJSONTyped(json, false)
}

export function JwtTokenSchoolResponseAllOfDataToJSONTyped(
    value?: JwtTokenSchoolResponseAllOfData | null,
    ignoreDiscriminator: boolean = false,
): any {
    if (value == null) {
        return value
    }

    return {
        token: value['token'],
        tokenExpiresIn: value['tokenExpiresIn'],
        id: value['id'],
        nr: value['nr'],
        name: value['name'],
        region: value['region'],
    }
}
