/* tslint:disable */
/* eslint-disable */
/**
 * Auth
 * Authentifizierungs-Endpunkte fuer api.inio.de/auth. Die Spezifikation bildet den bestehenden Auth-Flow mit API-Keys, Session-Token und Bearer-JWT ab.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime'
/**
 *
 * @export
 * @interface JwtTokenUserResponseAllOfData
 */
export interface JwtTokenUserResponseAllOfData {
    /**
     * JWT mit HS256 signiert
     * @type {string}
     * @memberof JwtTokenUserResponseAllOfData
     */
    token: string
    /**
     *
     * @type {number}
     * @memberof JwtTokenUserResponseAllOfData
     */
    tokenExpiresIn: number
    /**
     *
     * @type {number}
     * @memberof JwtTokenUserResponseAllOfData
     */
    userId: number
    /**
     *
     * @type {string}
     * @memberof JwtTokenUserResponseAllOfData
     */
    outname: string
}

/**
 * Check if a given object implements the JwtTokenUserResponseAllOfData interface.
 */
export function instanceOfJwtTokenUserResponseAllOfData(value: object): value is JwtTokenUserResponseAllOfData {
    if (!('token' in value) || value['token'] === undefined) return false
    if (!('tokenExpiresIn' in value) || value['tokenExpiresIn'] === undefined) return false
    if (!('userId' in value) || value['userId'] === undefined) return false
    if (!('outname' in value) || value['outname'] === undefined) return false
    return true
}

export function JwtTokenUserResponseAllOfDataFromJSON(json: any): JwtTokenUserResponseAllOfData {
    return JwtTokenUserResponseAllOfDataFromJSONTyped(json, false)
}

export function JwtTokenUserResponseAllOfDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): JwtTokenUserResponseAllOfData {
    if (json == null) {
        return json
    }
    return {
        token: json['token'],
        tokenExpiresIn: json['tokenExpiresIn'],
        userId: json['userId'],
        outname: json['outname'],
    }
}

export function JwtTokenUserResponseAllOfDataToJSON(json: any): JwtTokenUserResponseAllOfData {
    return JwtTokenUserResponseAllOfDataToJSONTyped(json, false)
}

export function JwtTokenUserResponseAllOfDataToJSONTyped(
    value?: JwtTokenUserResponseAllOfData | null,
    ignoreDiscriminator: boolean = false,
): any {
    if (value == null) {
        return value
    }

    return {
        token: value['token'],
        tokenExpiresIn: value['tokenExpiresIn'],
        userId: value['userId'],
        outname: value['outname'],
    }
}
