/* tslint:disable */
/* eslint-disable */
/**
 * Auth
 * Authentifizierungs-Endpunkte fuer api.inio.de/auth. Die Spezifikation bildet den bestehenden Auth-Flow mit API-Keys, Session-Token und Bearer-JWT ab.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime'
/**
 *
 * @export
 * @interface SchoolLoginRequest
 */
export interface SchoolLoginRequest {
    /**
     * Schulregion / Bundesland-Kuerzel
     * @type {string}
     * @memberof SchoolLoginRequest
     */
    region: string
    /**
     * Schulnummer
     * @type {string}
     * @memberof SchoolLoginRequest
     */
    schulNr: string
    /**
     * Passwort der Schule
     * @type {string}
     * @memberof SchoolLoginRequest
     */
    passwort: string
}

/**
 * Check if a given object implements the SchoolLoginRequest interface.
 */
export function instanceOfSchoolLoginRequest(value: object): value is SchoolLoginRequest {
    if (!('region' in value) || value['region'] === undefined) return false
    if (!('schulNr' in value) || value['schulNr'] === undefined) return false
    if (!('passwort' in value) || value['passwort'] === undefined) return false
    return true
}

export function SchoolLoginRequestFromJSON(json: any): SchoolLoginRequest {
    return SchoolLoginRequestFromJSONTyped(json, false)
}

export function SchoolLoginRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): SchoolLoginRequest {
    if (json == null) {
        return json
    }
    return {
        region: json['region'],
        schulNr: json['schulNr'],
        passwort: json['passwort'],
    }
}

export function SchoolLoginRequestToJSON(json: any): SchoolLoginRequest {
    return SchoolLoginRequestToJSONTyped(json, false)
}

export function SchoolLoginRequestToJSONTyped(value?: SchoolLoginRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value
    }

    return {
        region: value['region'],
        schulNr: value['schulNr'],
        passwort: value['passwort'],
    }
}
