/* tslint:disable */
/* eslint-disable */
/**
 * Auth
 * Authentifizierungs-Endpunkte fuer api.inio.de/auth. Die Spezifikation bildet den bestehenden Auth-Flow mit API-Keys, Session-Token und Bearer-JWT ab.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime'
/**
 *
 * @export
 * @interface StudentLoginRequest
 */
export interface StudentLoginRequest {
    /**
     * COLT-Kampagnen-ID
     * @type {number}
     * @memberof StudentLoginRequest
     */
    surveyId: number
    /**
     * Klassenpasswort des Schülers
     * @type {string}
     * @memberof StudentLoginRequest
     */
    loginPw: string
    /**
     * Login-Code des Schülers
     * @type {string}
     * @memberof StudentLoginRequest
     */
    loginCode: string
}

/**
 * Check if a given object implements the StudentLoginRequest interface.
 */
export function instanceOfStudentLoginRequest(value: object): value is StudentLoginRequest {
    if (!('surveyId' in value) || value['surveyId'] === undefined) return false
    if (!('loginPw' in value) || value['loginPw'] === undefined) return false
    if (!('loginCode' in value) || value['loginCode'] === undefined) return false
    return true
}

export function StudentLoginRequestFromJSON(json: any): StudentLoginRequest {
    return StudentLoginRequestFromJSONTyped(json, false)
}

export function StudentLoginRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): StudentLoginRequest {
    if (json == null) {
        return json
    }
    return {
        surveyId: json['surveyId'],
        loginPw: json['loginPw'],
        loginCode: json['loginCode'],
    }
}

export function StudentLoginRequestToJSON(json: any): StudentLoginRequest {
    return StudentLoginRequestToJSONTyped(json, false)
}

export function StudentLoginRequestToJSONTyped(value?: StudentLoginRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value
    }

    return {
        surveyId: value['surveyId'],
        loginPw: value['loginPw'],
        loginCode: value['loginCode'],
    }
}
