/* tslint:disable */
/* eslint-disable */
/**
 * TBA III
 * Diese API ermöglicht den Zugriff auf Auswertungsdaten von VERA. Sie bietet Endpunkte für die Abfrage von Leistungsdaten auf verschiedenen Ebenen (Lerngruppe, Schule, Bundesland) und für verschiedene Arten von Daten (Kompetenzstufen, Item-Statistiken, Aggregationen).
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime'
/**
 *
 * @export
 * @interface Aggregation
 */
export interface Aggregation {
    /**
     * Aggregationsart (z.B. Kompetenzstandard, Aufgabe), eigene Aggregationsarten können definiert werden.
     * @type {string}
     * @memberof Aggregation
     */
    type: string
    /**
     * Einzelne aggregierte Gruppe, z.B. der Aufgabenname, die Bezeichnung der Kompetenz, ...
     * @type {string}
     * @memberof Aggregation
     */
    value: string
    /**
     * Liste von IQB ItemIds, die in der Berechnung der Aggregation berücksichtigt wurden.
     * @type {Array<string>}
     * @memberof Aggregation
     */
    includedIqbIds?: Array<string>
}

/**
 * Check if a given object implements the Aggregation interface.
 */
export function instanceOfAggregation(value: object): value is Aggregation {
    if (!('type' in value) || value['type'] === undefined) return false
    if (!('value' in value) || value['value'] === undefined) return false
    return true
}

export function AggregationFromJSON(json: any): Aggregation {
    return AggregationFromJSONTyped(json, false)
}

export function AggregationFromJSONTyped(json: any, ignoreDiscriminator: boolean): Aggregation {
    if (json == null) {
        return json
    }
    return {
        type: json['type'],
        value: json['value'],
        includedIqbIds: json['includedIqbIds'] == null ? undefined : json['includedIqbIds'],
    }
}

export function AggregationToJSON(json: any): Aggregation {
    return AggregationToJSONTyped(json, false)
}

export function AggregationToJSONTyped(value?: Aggregation | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value
    }

    return {
        type: value['type'],
        value: value['value'],
        includedIqbIds: value['includedIqbIds'],
    }
}
