/* tslint:disable */
/* eslint-disable */
/**
 * TBA III
 * Diese API ermöglicht den Zugriff auf Auswertungsdaten von VERA. Sie bietet Endpunkte für die Abfrage von Leistungsdaten auf verschiedenen Ebenen (Lerngruppe, Schule, Bundesland) und für verschiedene Arten von Daten (Kompetenzstufen, Item-Statistiken, Aggregationen).
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime'
import type { DescriptiveStatisticsDescriptiveStatistics } from './DescriptiveStatisticsDescriptiveStatistics'
import {
    DescriptiveStatisticsDescriptiveStatisticsFromJSON,
    DescriptiveStatisticsDescriptiveStatisticsFromJSONTyped,
    DescriptiveStatisticsDescriptiveStatisticsToJSON,
    DescriptiveStatisticsDescriptiveStatisticsToJSONTyped,
} from './DescriptiveStatisticsDescriptiveStatistics'

/**
 *
 * @export
 * @interface AggregationsInnerAllOfAggregationsInner
 */
export interface AggregationsInnerAllOfAggregationsInner {
    /**
     * Aggregationsart (z.B. Kompetenzstandard, Aufgabe), eigene Aggregationsarten können definiert werden.
     * @type {string}
     * @memberof AggregationsInnerAllOfAggregationsInner
     */
    type: string
    /**
     * Einzelne aggregierte Gruppe, z.B. der Aufgabenname, die Bezeichnung der Kompetenz, ...
     * @type {string}
     * @memberof AggregationsInnerAllOfAggregationsInner
     */
    value: string
    /**
     * Liste von IQB ItemIds, die in der Berechnung der Aggregation berücksichtigt wurden.
     * @type {Array<string>}
     * @memberof AggregationsInnerAllOfAggregationsInner
     */
    includedIqbIds?: Array<string>
    /**
     *
     * @type {DescriptiveStatisticsDescriptiveStatistics}
     * @memberof AggregationsInnerAllOfAggregationsInner
     */
    descriptiveStatistics: DescriptiveStatisticsDescriptiveStatistics
}

/**
 * Check if a given object implements the AggregationsInnerAllOfAggregationsInner interface.
 */
export function instanceOfAggregationsInnerAllOfAggregationsInner(value: object): value is AggregationsInnerAllOfAggregationsInner {
    if (!('type' in value) || value['type'] === undefined) return false
    if (!('value' in value) || value['value'] === undefined) return false
    if (!('descriptiveStatistics' in value) || value['descriptiveStatistics'] === undefined) return false
    return true
}

export function AggregationsInnerAllOfAggregationsInnerFromJSON(json: any): AggregationsInnerAllOfAggregationsInner {
    return AggregationsInnerAllOfAggregationsInnerFromJSONTyped(json, false)
}

export function AggregationsInnerAllOfAggregationsInnerFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean,
): AggregationsInnerAllOfAggregationsInner {
    if (json == null) {
        return json
    }
    return {
        type: json['type'],
        value: json['value'],
        includedIqbIds: json['includedIqbIds'] == null ? undefined : json['includedIqbIds'],
        descriptiveStatistics: DescriptiveStatisticsDescriptiveStatisticsFromJSON(json['descriptiveStatistics']),
    }
}

export function AggregationsInnerAllOfAggregationsInnerToJSON(json: any): AggregationsInnerAllOfAggregationsInner {
    return AggregationsInnerAllOfAggregationsInnerToJSONTyped(json, false)
}

export function AggregationsInnerAllOfAggregationsInnerToJSONTyped(
    value?: AggregationsInnerAllOfAggregationsInner | null,
    ignoreDiscriminator: boolean = false,
): any {
    if (value == null) {
        return value
    }

    return {
        type: value['type'],
        value: value['value'],
        includedIqbIds: value['includedIqbIds'],
        descriptiveStatistics: DescriptiveStatisticsDescriptiveStatisticsToJSON(value['descriptiveStatistics']),
    }
}
