/* tslint:disable */
/* eslint-disable */
/**
 * TBA III
 * Diese API ermöglicht den Zugriff auf Auswertungsdaten von VERA. Sie bietet Endpunkte für die Abfrage von Leistungsdaten auf verschiedenen Ebenen (Lerngruppe, Schule, Bundesland) und für verschiedene Arten von Daten (Kompetenzstufen, Item-Statistiken, Aggregationen).
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime'
import type { ValueGroupPropertiesInner } from './ValueGroupPropertiesInner'
import {
    ValueGroupPropertiesInnerFromJSON,
    ValueGroupPropertiesInnerFromJSONTyped,
    ValueGroupPropertiesInnerToJSON,
    ValueGroupPropertiesInnerToJSONTyped,
} from './ValueGroupPropertiesInner'
import type { Characteristic } from './Characteristic'
import { CharacteristicFromJSON, CharacteristicFromJSONTyped, CharacteristicToJSON, CharacteristicToJSONTyped } from './Characteristic'
import type { Domain } from './Domain'
import { DomainFromJSON, DomainFromJSONTyped, DomainToJSON, DomainToJSONTyped } from './Domain'
import type { AggregationsInnerAllOfAggregationsInner } from './AggregationsInnerAllOfAggregationsInner'
import {
    AggregationsInnerAllOfAggregationsInnerFromJSON,
    AggregationsInnerAllOfAggregationsInnerFromJSONTyped,
    AggregationsInnerAllOfAggregationsInnerToJSON,
    AggregationsInnerAllOfAggregationsInnerToJSONTyped,
} from './AggregationsInnerAllOfAggregationsInner'
import type { Subject } from './Subject'
import { SubjectFromJSON, SubjectFromJSONTyped, SubjectToJSON, SubjectToJSONTyped } from './Subject'

/**
 *
 * @export
 * @interface AggregationsInner
 */
export interface AggregationsInner {
    /**
     *
     * @type {string}
     * @memberof AggregationsInner
     */
    id?: string
    /**
     * Bezeichnung der Wertegruppe
     * @type {string}
     * @memberof AggregationsInner
     */
    name: string
    /**
     * Domäne der Wertegruppe (optional)
     * @type {Domain}
     * @memberof AggregationsInner
     */
    domain?: Domain
    /**
     * Fach der Wertegruppe (optional)
     * @type {Subject}
     * @memberof AggregationsInner
     */
    subject?: Subject
    /**
     * Kovariaten der Wertegruppe
     * @type {Array<Characteristic>}
     * @memberof AggregationsInner
     */
    covariates?: Array<Characteristic>
    /**
     * Liste von Key-Value-Werten mit zusätzlichen Informationen, z.B. Testdauer, andere systemspezifische Attribute
     * @type {Array<ValueGroupPropertiesInner>}
     * @memberof AggregationsInner
     */
    properties?: Array<ValueGroupPropertiesInner>
    /**
     * Einzelne Aggregationen
     * @type {Array<AggregationsInnerAllOfAggregationsInner>}
     * @memberof AggregationsInner
     */
    aggregations: Array<AggregationsInnerAllOfAggregationsInner>
}

/**
 * Check if a given object implements the AggregationsInner interface.
 */
export function instanceOfAggregationsInner(value: object): value is AggregationsInner {
    if (!('name' in value) || value['name'] === undefined) return false
    if (!('aggregations' in value) || value['aggregations'] === undefined) return false
    return true
}

export function AggregationsInnerFromJSON(json: any): AggregationsInner {
    return AggregationsInnerFromJSONTyped(json, false)
}

export function AggregationsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): AggregationsInner {
    if (json == null) {
        return json
    }
    return {
        id: json['id'] == null ? undefined : json['id'],
        name: json['name'],
        domain: json['domain'] == null ? undefined : DomainFromJSON(json['domain']),
        subject: json['subject'] == null ? undefined : SubjectFromJSON(json['subject']),
        covariates: json['covariates'] == null ? undefined : (json['covariates'] as Array<any>).map(CharacteristicFromJSON),
        properties: json['properties'] == null ? undefined : (json['properties'] as Array<any>).map(ValueGroupPropertiesInnerFromJSON),
        aggregations: (json['aggregations'] as Array<any>).map(AggregationsInnerAllOfAggregationsInnerFromJSON),
    }
}

export function AggregationsInnerToJSON(json: any): AggregationsInner {
    return AggregationsInnerToJSONTyped(json, false)
}

export function AggregationsInnerToJSONTyped(value?: AggregationsInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value
    }

    return {
        id: value['id'],
        name: value['name'],
        domain: DomainToJSON(value['domain']),
        subject: SubjectToJSON(value['subject']),
        covariates: value['covariates'] == null ? undefined : (value['covariates'] as Array<any>).map(CharacteristicToJSON),
        properties: value['properties'] == null ? undefined : (value['properties'] as Array<any>).map(ValueGroupPropertiesInnerToJSON),
        aggregations: (value['aggregations'] as Array<any>).map(AggregationsInnerAllOfAggregationsInnerToJSON),
    }
}
