/* tslint:disable */
/* eslint-disable */
/**
 * TBA III
 * Diese API ermöglicht den Zugriff auf Auswertungsdaten von VERA. Sie bietet Endpunkte für die Abfrage von Leistungsdaten auf verschiedenen Ebenen (Lerngruppe, Schule, Bundesland) und für verschiedene Arten von Daten (Kompetenzstufen, Item-Statistiken, Aggregationen).
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { GenderCharacteristic } from './GenderCharacteristic'
import {
    instanceOfGenderCharacteristic,
    GenderCharacteristicFromJSON,
    GenderCharacteristicFromJSONTyped,
    GenderCharacteristicToJSON,
} from './GenderCharacteristic'
import type { LanguageAtHomeCharacteristic } from './LanguageAtHomeCharacteristic'
import {
    instanceOfLanguageAtHomeCharacteristic,
    LanguageAtHomeCharacteristicFromJSON,
    LanguageAtHomeCharacteristicFromJSONTyped,
    LanguageAtHomeCharacteristicToJSON,
} from './LanguageAtHomeCharacteristic'
import type { OtherCharacteristic } from './OtherCharacteristic'
import {
    instanceOfOtherCharacteristic,
    OtherCharacteristicFromJSON,
    OtherCharacteristicFromJSONTyped,
    OtherCharacteristicToJSON,
} from './OtherCharacteristic'

/**
 * @type Characteristic
 *
 * @export
 */
export type Characteristic =
    | ({ type: 'gender' } & GenderCharacteristic)
    | ({ type: 'languageAtHome' } & LanguageAtHomeCharacteristic)
    | ({ type: 'other' } & OtherCharacteristic)

export function CharacteristicFromJSON(json: any): Characteristic {
    return CharacteristicFromJSONTyped(json, false)
}

export function CharacteristicFromJSONTyped(json: any, ignoreDiscriminator: boolean): Characteristic {
    if (json == null) {
        return json
    }
    switch (json['type']) {
        case 'gender':
            return Object.assign({}, GenderCharacteristicFromJSONTyped(json, true), { type: 'gender' } as const)
        case 'languageAtHome':
            return Object.assign({}, LanguageAtHomeCharacteristicFromJSONTyped(json, true), { type: 'languageAtHome' } as const)
        case 'other':
            return Object.assign({}, OtherCharacteristicFromJSONTyped(json, true), { type: 'other' } as const)
        default:
            return json
    }
}

export function CharacteristicToJSON(json: any): any {
    return CharacteristicToJSONTyped(json, false)
}

export function CharacteristicToJSONTyped(value?: Characteristic | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value
    }
    switch (value['type']) {
        case 'gender':
            return Object.assign({}, GenderCharacteristicToJSON(value), { type: 'gender' } as const)
        case 'languageAtHome':
            return Object.assign({}, LanguageAtHomeCharacteristicToJSON(value), { type: 'languageAtHome' } as const)
        case 'other':
            return Object.assign({}, OtherCharacteristicToJSON(value), { type: 'other' } as const)
        default:
            return value
    }
}
