/* tslint:disable */
/* eslint-disable */
/**
 * TBA III
 * Diese API ermöglicht den Zugriff auf Auswertungsdaten von VERA. Sie bietet Endpunkte für die Abfrage von Leistungsdaten auf verschiedenen Ebenen (Lerngruppe, Schule, Bundesland) und für verschiedene Arten von Daten (Kompetenzstufen, Item-Statistiken, Aggregationen).
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime'
/**
 *
 * @export
 * @interface Competence
 */
export interface Competence {
    /**
     *
     * @type {string}
     * @memberof Competence
     */
    id?: string
    /**
     * Art der Kompetenz
     * @type {string}
     * @memberof Competence
     */
    type?: string
    /**
     * Name der Kompetenz
     * @type {string}
     * @memberof Competence
     */
    name?: string
    /**
     * Beschreibung der Kompetenz
     * @type {string}
     * @memberof Competence
     */
    description?: string
}

/**
 * Check if a given object implements the Competence interface.
 */
export function instanceOfCompetence(value: object): value is Competence {
    return true
}

export function CompetenceFromJSON(json: any): Competence {
    return CompetenceFromJSONTyped(json, false)
}

export function CompetenceFromJSONTyped(json: any, ignoreDiscriminator: boolean): Competence {
    if (json == null) {
        return json
    }
    return {
        id: json['id'] == null ? undefined : json['id'],
        type: json['type'] == null ? undefined : json['type'],
        name: json['name'] == null ? undefined : json['name'],
        description: json['description'] == null ? undefined : json['description'],
    }
}

export function CompetenceToJSON(json: any): Competence {
    return CompetenceToJSONTyped(json, false)
}

export function CompetenceToJSONTyped(value?: Competence | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value
    }

    return {
        id: value['id'],
        type: value['type'],
        name: value['name'],
        description: value['description'],
    }
}
