/* tslint:disable */
/* eslint-disable */
/**
 * TBA III
 * Diese API ermöglicht den Zugriff auf Auswertungsdaten von VERA. Sie bietet Endpunkte für die Abfrage von Leistungsdaten auf verschiedenen Ebenen (Lerngruppe, Schule, Bundesland) und für verschiedene Arten von Daten (Kompetenzstufen, Item-Statistiken, Aggregationen).
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime'
import type { CompetenceLevelDescriptiveStatisticsDescriptiveStatistics } from './CompetenceLevelDescriptiveStatisticsDescriptiveStatistics'
import {
    CompetenceLevelDescriptiveStatisticsDescriptiveStatisticsFromJSON,
    CompetenceLevelDescriptiveStatisticsDescriptiveStatisticsFromJSONTyped,
    CompetenceLevelDescriptiveStatisticsDescriptiveStatisticsToJSON,
    CompetenceLevelDescriptiveStatisticsDescriptiveStatisticsToJSONTyped,
} from './CompetenceLevelDescriptiveStatisticsDescriptiveStatistics'

/**
 *
 * @export
 * @interface CompetenceLevelStatisticsInner
 */
export interface CompetenceLevelStatisticsInner {
    /**
     *
     * @type {string}
     * @memberof CompetenceLevelStatisticsInner
     */
    id?: string
    /**
     * Name der Komptenzstufe
     * @type {string}
     * @memberof CompetenceLevelStatisticsInner
     */
    name?: string
    /**
     * Kürzel der Kompetenzstufe
     * @type {string}
     * @memberof CompetenceLevelStatisticsInner
     */
    nameShort: string
    /**
     * Beschreibung der Kompetenzstufe
     * @type {string}
     * @memberof CompetenceLevelStatisticsInner
     */
    description?: string
    /**
     *
     * @type {CompetenceLevelDescriptiveStatisticsDescriptiveStatistics}
     * @memberof CompetenceLevelStatisticsInner
     */
    descriptiveStatistics: CompetenceLevelDescriptiveStatisticsDescriptiveStatistics
}

/**
 * Check if a given object implements the CompetenceLevelStatisticsInner interface.
 */
export function instanceOfCompetenceLevelStatisticsInner(value: object): value is CompetenceLevelStatisticsInner {
    if (!('nameShort' in value) || value['nameShort'] === undefined) return false
    if (!('descriptiveStatistics' in value) || value['descriptiveStatistics'] === undefined) return false
    return true
}

export function CompetenceLevelStatisticsInnerFromJSON(json: any): CompetenceLevelStatisticsInner {
    return CompetenceLevelStatisticsInnerFromJSONTyped(json, false)
}

export function CompetenceLevelStatisticsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): CompetenceLevelStatisticsInner {
    if (json == null) {
        return json
    }
    return {
        id: json['id'] == null ? undefined : json['id'],
        name: json['name'] == null ? undefined : json['name'],
        nameShort: json['nameShort'],
        description: json['description'] == null ? undefined : json['description'],
        descriptiveStatistics: CompetenceLevelDescriptiveStatisticsDescriptiveStatisticsFromJSON(json['descriptiveStatistics']),
    }
}

export function CompetenceLevelStatisticsInnerToJSON(json: any): CompetenceLevelStatisticsInner {
    return CompetenceLevelStatisticsInnerToJSONTyped(json, false)
}

export function CompetenceLevelStatisticsInnerToJSONTyped(
    value?: CompetenceLevelStatisticsInner | null,
    ignoreDiscriminator: boolean = false,
): any {
    if (value == null) {
        return value
    }

    return {
        id: value['id'],
        name: value['name'],
        nameShort: value['nameShort'],
        description: value['description'],
        descriptiveStatistics: CompetenceLevelDescriptiveStatisticsDescriptiveStatisticsToJSON(value['descriptiveStatistics']),
    }
}
