/* tslint:disable */
/* eslint-disable */
/**
 * TBA III
 * Diese API ermöglicht den Zugriff auf Auswertungsdaten von VERA. Sie bietet Endpunkte für die Abfrage von Leistungsdaten auf verschiedenen Ebenen (Lerngruppe, Schule, Bundesland) und für verschiedene Arten von Daten (Kompetenzstufen, Item-Statistiken, Aggregationen).
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime'
/**
 *
 * @export
 * @interface CompetenceLevel
 */
export interface CompetenceLevel {
    /**
     *
     * @type {string}
     * @memberof CompetenceLevel
     */
    id?: string
    /**
     * Name der Komptenzstufe
     * @type {string}
     * @memberof CompetenceLevel
     */
    name?: string
    /**
     * Kürzel der Kompetenzstufe
     * @type {string}
     * @memberof CompetenceLevel
     */
    nameShort: string
    /**
     * Beschreibung der Kompetenzstufe
     * @type {string}
     * @memberof CompetenceLevel
     */
    description?: string
}

/**
 * Check if a given object implements the CompetenceLevel interface.
 */
export function instanceOfCompetenceLevel(value: object): value is CompetenceLevel {
    if (!('nameShort' in value) || value['nameShort'] === undefined) return false
    return true
}

export function CompetenceLevelFromJSON(json: any): CompetenceLevel {
    return CompetenceLevelFromJSONTyped(json, false)
}

export function CompetenceLevelFromJSONTyped(json: any, ignoreDiscriminator: boolean): CompetenceLevel {
    if (json == null) {
        return json
    }
    return {
        id: json['id'] == null ? undefined : json['id'],
        name: json['name'] == null ? undefined : json['name'],
        nameShort: json['nameShort'],
        description: json['description'] == null ? undefined : json['description'],
    }
}

export function CompetenceLevelToJSON(json: any): CompetenceLevel {
    return CompetenceLevelToJSONTyped(json, false)
}

export function CompetenceLevelToJSONTyped(value?: CompetenceLevel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value
    }

    return {
        id: value['id'],
        name: value['name'],
        nameShort: value['nameShort'],
        description: value['description'],
    }
}
