/* tslint:disable */
/* eslint-disable */
/**
 * TBA III
 * Diese API ermöglicht den Zugriff auf Auswertungsdaten von VERA. Sie bietet Endpunkte für die Abfrage von Leistungsdaten auf verschiedenen Ebenen (Lerngruppe, Schule, Bundesland) und für verschiedene Arten von Daten (Kompetenzstufen, Item-Statistiken, Aggregationen).
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime'
/**
 *
 * @export
 * @interface CompetenceLevelDescriptiveStatisticsDescriptiveStatistics
 */
export interface CompetenceLevelDescriptiveStatisticsDescriptiveStatistics {
    /**
     * Gesamtzahl der Schüler:innen in der Wertegruppe
     * @type {number}
     * @memberof CompetenceLevelDescriptiveStatisticsDescriptiveStatistics
     */
    total: number
    /**
     * Anteil der Schüler:innen an der Gesamtzahl, die diese Kompetenzstufe erreicht haben.
     * @type {number}
     * @memberof CompetenceLevelDescriptiveStatisticsDescriptiveStatistics
     */
    mean: number
    /**
     * Anzahl der Schüler:innen, die diese Kompetenzstufe erreicht haben.
     * @type {number}
     * @memberof CompetenceLevelDescriptiveStatisticsDescriptiveStatistics
     */
    frequency: number
}

/**
 * Check if a given object implements the CompetenceLevelDescriptiveStatisticsDescriptiveStatistics interface.
 */
export function instanceOfCompetenceLevelDescriptiveStatisticsDescriptiveStatistics(
    value: object,
): value is CompetenceLevelDescriptiveStatisticsDescriptiveStatistics {
    if (!('total' in value) || value['total'] === undefined) return false
    if (!('mean' in value) || value['mean'] === undefined) return false
    if (!('frequency' in value) || value['frequency'] === undefined) return false
    return true
}

export function CompetenceLevelDescriptiveStatisticsDescriptiveStatisticsFromJSON(
    json: any,
): CompetenceLevelDescriptiveStatisticsDescriptiveStatistics {
    return CompetenceLevelDescriptiveStatisticsDescriptiveStatisticsFromJSONTyped(json, false)
}

export function CompetenceLevelDescriptiveStatisticsDescriptiveStatisticsFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean,
): CompetenceLevelDescriptiveStatisticsDescriptiveStatistics {
    if (json == null) {
        return json
    }
    return {
        total: json['total'],
        mean: json['mean'],
        frequency: json['frequency'],
    }
}

export function CompetenceLevelDescriptiveStatisticsDescriptiveStatisticsToJSON(
    json: any,
): CompetenceLevelDescriptiveStatisticsDescriptiveStatistics {
    return CompetenceLevelDescriptiveStatisticsDescriptiveStatisticsToJSONTyped(json, false)
}

export function CompetenceLevelDescriptiveStatisticsDescriptiveStatisticsToJSONTyped(
    value?: CompetenceLevelDescriptiveStatisticsDescriptiveStatistics | null,
    ignoreDiscriminator: boolean = false,
): any {
    if (value == null) {
        return value
    }

    return {
        total: value['total'],
        mean: value['mean'],
        frequency: value['frequency'],
    }
}
