/* tslint:disable */
/* eslint-disable */
/**
 * TBA III
 * Diese API ermöglicht den Zugriff auf Auswertungsdaten von VERA. Sie bietet Endpunkte für die Abfrage von Leistungsdaten auf verschiedenen Ebenen (Lerngruppe, Schule, Bundesland) und für verschiedene Arten von Daten (Kompetenzstufen, Item-Statistiken, Aggregationen).
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime'
import type { CompetenceLevelStatisticsInner } from './CompetenceLevelStatisticsInner'
import {
    CompetenceLevelStatisticsInnerFromJSON,
    CompetenceLevelStatisticsInnerFromJSONTyped,
    CompetenceLevelStatisticsInnerToJSON,
    CompetenceLevelStatisticsInnerToJSONTyped,
} from './CompetenceLevelStatisticsInner'
import type { ValueGroupPropertiesInner } from './ValueGroupPropertiesInner'
import {
    ValueGroupPropertiesInnerFromJSON,
    ValueGroupPropertiesInnerFromJSONTyped,
    ValueGroupPropertiesInnerToJSON,
    ValueGroupPropertiesInnerToJSONTyped,
} from './ValueGroupPropertiesInner'
import type { Characteristic } from './Characteristic'
import { CharacteristicFromJSON, CharacteristicFromJSONTyped, CharacteristicToJSON, CharacteristicToJSONTyped } from './Characteristic'
import type { Domain } from './Domain'
import { DomainFromJSON, DomainFromJSONTyped, DomainToJSON, DomainToJSONTyped } from './Domain'
import type { Subject } from './Subject'
import { SubjectFromJSON, SubjectFromJSONTyped, SubjectToJSON, SubjectToJSONTyped } from './Subject'

/**
 *
 * @export
 * @interface CompetenceLevelsInner
 */
export interface CompetenceLevelsInner {
    /**
     *
     * @type {string}
     * @memberof CompetenceLevelsInner
     */
    id?: string
    /**
     * Bezeichnung der Wertegruppe
     * @type {string}
     * @memberof CompetenceLevelsInner
     */
    name: string
    /**
     * Domäne der Wertegruppe (optional)
     * @type {Domain}
     * @memberof CompetenceLevelsInner
     */
    domain?: Domain
    /**
     * Fach der Wertegruppe (optional)
     * @type {Subject}
     * @memberof CompetenceLevelsInner
     */
    subject?: Subject
    /**
     * Kovariaten der Wertegruppe
     * @type {Array<Characteristic>}
     * @memberof CompetenceLevelsInner
     */
    covariates?: Array<Characteristic>
    /**
     * Liste von Key-Value-Werten mit zusätzlichen Informationen, z.B. Testdauer, andere systemspezifische Attribute
     * @type {Array<ValueGroupPropertiesInner>}
     * @memberof CompetenceLevelsInner
     */
    properties?: Array<ValueGroupPropertiesInner>
    /**
     * Kompetenzstufenverteilung in der Wertegruppe
     * @type {Array<CompetenceLevelStatisticsInner>}
     * @memberof CompetenceLevelsInner
     */
    competenceLevels: Array<CompetenceLevelStatisticsInner>
}

/**
 * Check if a given object implements the CompetenceLevelsInner interface.
 */
export function instanceOfCompetenceLevelsInner(value: object): value is CompetenceLevelsInner {
    if (!('name' in value) || value['name'] === undefined) return false
    if (!('competenceLevels' in value) || value['competenceLevels'] === undefined) return false
    return true
}

export function CompetenceLevelsInnerFromJSON(json: any): CompetenceLevelsInner {
    return CompetenceLevelsInnerFromJSONTyped(json, false)
}

export function CompetenceLevelsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): CompetenceLevelsInner {
    if (json == null) {
        return json
    }
    return {
        id: json['id'] == null ? undefined : json['id'],
        name: json['name'],
        domain: json['domain'] == null ? undefined : DomainFromJSON(json['domain']),
        subject: json['subject'] == null ? undefined : SubjectFromJSON(json['subject']),
        covariates: json['covariates'] == null ? undefined : (json['covariates'] as Array<any>).map(CharacteristicFromJSON),
        properties: json['properties'] == null ? undefined : (json['properties'] as Array<any>).map(ValueGroupPropertiesInnerFromJSON),
        competenceLevels: (json['competenceLevels'] as Array<any>).map(CompetenceLevelStatisticsInnerFromJSON),
    }
}

export function CompetenceLevelsInnerToJSON(json: any): CompetenceLevelsInner {
    return CompetenceLevelsInnerToJSONTyped(json, false)
}

export function CompetenceLevelsInnerToJSONTyped(value?: CompetenceLevelsInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value
    }

    return {
        id: value['id'],
        name: value['name'],
        domain: DomainToJSON(value['domain']),
        subject: SubjectToJSON(value['subject']),
        covariates: value['covariates'] == null ? undefined : (value['covariates'] as Array<any>).map(CharacteristicToJSON),
        properties: value['properties'] == null ? undefined : (value['properties'] as Array<any>).map(ValueGroupPropertiesInnerToJSON),
        competenceLevels: (value['competenceLevels'] as Array<any>).map(CompetenceLevelStatisticsInnerToJSON),
    }
}
