/* tslint:disable */
/* eslint-disable */
/**
 * TBA III
 * Diese API ermöglicht den Zugriff auf Auswertungsdaten von VERA. Sie bietet Endpunkte für die Abfrage von Leistungsdaten auf verschiedenen Ebenen (Lerngruppe, Schule, Bundesland) und für verschiedene Arten von Daten (Kompetenzstufen, Item-Statistiken, Aggregationen).
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime'
import type { CompetenceLevelDescriptiveStatisticsDescriptiveStatistics } from './CompetenceLevelDescriptiveStatisticsDescriptiveStatistics'
import {
    CompetenceLevelDescriptiveStatisticsDescriptiveStatisticsFromJSON,
    CompetenceLevelDescriptiveStatisticsDescriptiveStatisticsFromJSONTyped,
    CompetenceLevelDescriptiveStatisticsDescriptiveStatisticsToJSON,
    CompetenceLevelDescriptiveStatisticsDescriptiveStatisticsToJSONTyped,
} from './CompetenceLevelDescriptiveStatisticsDescriptiveStatistics'

/**
 *
 * @export
 * @interface CompetenceLevelDescriptiveStatistics
 */
export interface CompetenceLevelDescriptiveStatistics {
    /**
     *
     * @type {CompetenceLevelDescriptiveStatisticsDescriptiveStatistics}
     * @memberof CompetenceLevelDescriptiveStatistics
     */
    descriptiveStatistics: CompetenceLevelDescriptiveStatisticsDescriptiveStatistics
}

/**
 * Check if a given object implements the CompetenceLevelDescriptiveStatistics interface.
 */
export function instanceOfCompetenceLevelDescriptiveStatistics(value: object): value is CompetenceLevelDescriptiveStatistics {
    if (!('descriptiveStatistics' in value) || value['descriptiveStatistics'] === undefined) return false
    return true
}

export function CompetenceLevelDescriptiveStatisticsFromJSON(json: any): CompetenceLevelDescriptiveStatistics {
    return CompetenceLevelDescriptiveStatisticsFromJSONTyped(json, false)
}

export function CompetenceLevelDescriptiveStatisticsFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean,
): CompetenceLevelDescriptiveStatistics {
    if (json == null) {
        return json
    }
    return {
        descriptiveStatistics: CompetenceLevelDescriptiveStatisticsDescriptiveStatisticsFromJSON(json['descriptiveStatistics']),
    }
}

export function CompetenceLevelDescriptiveStatisticsToJSON(json: any): CompetenceLevelDescriptiveStatistics {
    return CompetenceLevelDescriptiveStatisticsToJSONTyped(json, false)
}

export function CompetenceLevelDescriptiveStatisticsToJSONTyped(
    value?: CompetenceLevelDescriptiveStatistics | null,
    ignoreDiscriminator: boolean = false,
): any {
    if (value == null) {
        return value
    }

    return {
        descriptiveStatistics: CompetenceLevelDescriptiveStatisticsDescriptiveStatisticsToJSON(value['descriptiveStatistics']),
    }
}
