/* tslint:disable */
/* eslint-disable */
/**
 * TBA III
 * Diese API ermöglicht den Zugriff auf Auswertungsdaten von VERA. Sie bietet Endpunkte für die Abfrage von Leistungsdaten auf verschiedenen Ebenen (Lerngruppe, Schule, Bundesland) und für verschiedene Arten von Daten (Kompetenzstufen, Item-Statistiken, Aggregationen).
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime'
/**
 *
 * @export
 * @interface DescriptiveStatisticsDescriptiveStatistics
 */
export interface DescriptiveStatisticsDescriptiveStatistics {
    /**
     * Gesamtzahl der Items
     * @type {number}
     * @memberof DescriptiveStatisticsDescriptiveStatistics
     */
    total: number
    /**
     * Anteil richtig gelöster Items / Mittlere Lösungsquote
     * @type {number}
     * @memberof DescriptiveStatisticsDescriptiveStatistics
     */
    mean: number
    /**
     * Absolute Anzahl richtig gelöster Items
     * @type {number}
     * @memberof DescriptiveStatisticsDescriptiveStatistics
     */
    frequency: number
    /**
     * Standardabweichung der mittleren Lösungsquote
     * @type {number}
     * @memberof DescriptiveStatisticsDescriptiveStatistics
     */
    standardDeviation: number
}

/**
 * Check if a given object implements the DescriptiveStatisticsDescriptiveStatistics interface.
 */
export function instanceOfDescriptiveStatisticsDescriptiveStatistics(value: object): value is DescriptiveStatisticsDescriptiveStatistics {
    if (!('total' in value) || value['total'] === undefined) return false
    if (!('mean' in value) || value['mean'] === undefined) return false
    if (!('frequency' in value) || value['frequency'] === undefined) return false
    if (!('standardDeviation' in value) || value['standardDeviation'] === undefined) return false
    return true
}

export function DescriptiveStatisticsDescriptiveStatisticsFromJSON(json: any): DescriptiveStatisticsDescriptiveStatistics {
    return DescriptiveStatisticsDescriptiveStatisticsFromJSONTyped(json, false)
}

export function DescriptiveStatisticsDescriptiveStatisticsFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean,
): DescriptiveStatisticsDescriptiveStatistics {
    if (json == null) {
        return json
    }
    return {
        total: json['total'],
        mean: json['mean'],
        frequency: json['frequency'],
        standardDeviation: json['standardDeviation'],
    }
}

export function DescriptiveStatisticsDescriptiveStatisticsToJSON(json: any): DescriptiveStatisticsDescriptiveStatistics {
    return DescriptiveStatisticsDescriptiveStatisticsToJSONTyped(json, false)
}

export function DescriptiveStatisticsDescriptiveStatisticsToJSONTyped(
    value?: DescriptiveStatisticsDescriptiveStatistics | null,
    ignoreDiscriminator: boolean = false,
): any {
    if (value == null) {
        return value
    }

    return {
        total: value['total'],
        mean: value['mean'],
        frequency: value['frequency'],
        standardDeviation: value['standardDeviation'],
    }
}
