/* tslint:disable */
/* eslint-disable */
/**
 * TBA III
 * Diese API ermöglicht den Zugriff auf Auswertungsdaten von VERA. Sie bietet Endpunkte für die Abfrage von Leistungsdaten auf verschiedenen Ebenen (Lerngruppe, Schule, Bundesland) und für verschiedene Arten von Daten (Kompetenzstufen, Item-Statistiken, Aggregationen).
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime'
import type { DescriptiveStatisticsDescriptiveStatistics } from './DescriptiveStatisticsDescriptiveStatistics'
import {
    DescriptiveStatisticsDescriptiveStatisticsFromJSON,
    DescriptiveStatisticsDescriptiveStatisticsFromJSONTyped,
    DescriptiveStatisticsDescriptiveStatisticsToJSON,
    DescriptiveStatisticsDescriptiveStatisticsToJSONTyped,
} from './DescriptiveStatisticsDescriptiveStatistics'

/**
 *
 * @export
 * @interface DescriptiveStatistics
 */
export interface DescriptiveStatistics {
    /**
     *
     * @type {DescriptiveStatisticsDescriptiveStatistics}
     * @memberof DescriptiveStatistics
     */
    descriptiveStatistics: DescriptiveStatisticsDescriptiveStatistics
}

/**
 * Check if a given object implements the DescriptiveStatistics interface.
 */
export function instanceOfDescriptiveStatistics(value: object): value is DescriptiveStatistics {
    if (!('descriptiveStatistics' in value) || value['descriptiveStatistics'] === undefined) return false
    return true
}

export function DescriptiveStatisticsFromJSON(json: any): DescriptiveStatistics {
    return DescriptiveStatisticsFromJSONTyped(json, false)
}

export function DescriptiveStatisticsFromJSONTyped(json: any, ignoreDiscriminator: boolean): DescriptiveStatistics {
    if (json == null) {
        return json
    }
    return {
        descriptiveStatistics: DescriptiveStatisticsDescriptiveStatisticsFromJSON(json['descriptiveStatistics']),
    }
}

export function DescriptiveStatisticsToJSON(json: any): DescriptiveStatistics {
    return DescriptiveStatisticsToJSONTyped(json, false)
}

export function DescriptiveStatisticsToJSONTyped(value?: DescriptiveStatistics | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value
    }

    return {
        descriptiveStatistics: DescriptiveStatisticsDescriptiveStatisticsToJSON(value['descriptiveStatistics']),
    }
}
