/* tslint:disable */
/* eslint-disable */
/**
 * TBA III
 * Diese API ermöglicht den Zugriff auf Auswertungsdaten von VERA. Sie bietet Endpunkte für die Abfrage von Leistungsdaten auf verschiedenen Ebenen (Lerngruppe, Schule, Bundesland) und für verschiedene Arten von Daten (Kompetenzstufen, Item-Statistiken, Aggregationen).
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime'
/**
 *
 * @export
 * @interface Domain
 */
export interface Domain {
    /**
     *
     * @type {string}
     * @memberof Domain
     */
    id?: string
    /**
     * Name der Domäne
     * @type {string}
     * @memberof Domain
     */
    name: string
}

/**
 * Check if a given object implements the Domain interface.
 */
export function instanceOfDomain(value: object): value is Domain {
    if (!('name' in value) || value['name'] === undefined) return false
    return true
}

export function DomainFromJSON(json: any): Domain {
    return DomainFromJSONTyped(json, false)
}

export function DomainFromJSONTyped(json: any, ignoreDiscriminator: boolean): Domain {
    if (json == null) {
        return json
    }
    return {
        id: json['id'] == null ? undefined : json['id'],
        name: json['name'],
    }
}

export function DomainToJSON(json: any): Domain {
    return DomainToJSONTyped(json, false)
}

export function DomainToJSONTyped(value?: Domain | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value
    }

    return {
        id: value['id'],
        name: value['name'],
    }
}
