/* tslint:disable */
/* eslint-disable */
/**
 * TBA III
 * Diese API ermöglicht den Zugriff auf Auswertungsdaten von VERA. Sie bietet Endpunkte für die Abfrage von Leistungsdaten auf verschiedenen Ebenen (Lerngruppe, Schule, Bundesland) und für verschiedene Arten von Daten (Kompetenzstufen, Item-Statistiken, Aggregationen).
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime'
/**
 *
 * @export
 * @interface Exercise
 */
export interface Exercise {
    /**
     *
     * @type {string}
     * @memberof Exercise
     */
    id?: string
    /**
     * Name der Aufgabe
     * @type {string}
     * @memberof Exercise
     */
    name: string
}

/**
 * Check if a given object implements the Exercise interface.
 */
export function instanceOfExercise(value: object): value is Exercise {
    if (!('name' in value) || value['name'] === undefined) return false
    return true
}

export function ExerciseFromJSON(json: any): Exercise {
    return ExerciseFromJSONTyped(json, false)
}

export function ExerciseFromJSONTyped(json: any, ignoreDiscriminator: boolean): Exercise {
    if (json == null) {
        return json
    }
    return {
        id: json['id'] == null ? undefined : json['id'],
        name: json['name'],
    }
}

export function ExerciseToJSON(json: any): Exercise {
    return ExerciseToJSONTyped(json, false)
}

export function ExerciseToJSONTyped(value?: Exercise | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value
    }

    return {
        id: value['id'],
        name: value['name'],
    }
}
