/* tslint:disable */
/* eslint-disable */
/**
 * TBA III
 * Diese API ermöglicht den Zugriff auf Auswertungsdaten von VERA. Sie bietet Endpunkte für die Abfrage von Leistungsdaten auf verschiedenen Ebenen (Lerngruppe, Schule, Bundesland) und für verschiedene Arten von Daten (Kompetenzstufen, Item-Statistiken, Aggregationen).
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime'
/**
 *
 * @export
 * @interface GenderCharacteristic
 */
export interface GenderCharacteristic {
    /**
     * Type of characteristic
     * @type {GenderCharacteristicTypeEnum}
     * @memberof GenderCharacteristic
     */
    type: GenderCharacteristicTypeEnum
    /**
     * Label for the characteristic
     * @type {string}
     * @memberof GenderCharacteristic
     */
    label?: string
    /**
     * Specific value of the characteristic
     * @type {string}
     * @memberof GenderCharacteristic
     */
    value: string
}

/**
 * @export
 */
export const GenderCharacteristicTypeEnum = {
    Gender: 'gender',
} as const
export type GenderCharacteristicTypeEnum = (typeof GenderCharacteristicTypeEnum)[keyof typeof GenderCharacteristicTypeEnum]

/**
 * Check if a given object implements the GenderCharacteristic interface.
 */
export function instanceOfGenderCharacteristic(value: object): value is GenderCharacteristic {
    if (!('type' in value) || value['type'] === undefined) return false
    if (!('value' in value) || value['value'] === undefined) return false
    return true
}

export function GenderCharacteristicFromJSON(json: any): GenderCharacteristic {
    return GenderCharacteristicFromJSONTyped(json, false)
}

export function GenderCharacteristicFromJSONTyped(json: any, ignoreDiscriminator: boolean): GenderCharacteristic {
    if (json == null) {
        return json
    }
    return {
        type: json['type'],
        label: json['label'] == null ? undefined : json['label'],
        value: json['value'],
    }
}

export function GenderCharacteristicToJSON(json: any): GenderCharacteristic {
    return GenderCharacteristicToJSONTyped(json, false)
}

export function GenderCharacteristicToJSONTyped(value?: GenderCharacteristic | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value
    }

    return {
        type: value['type'],
        label: value['label'],
        value: value['value'],
    }
}
