/* tslint:disable */
/* eslint-disable */
export * from './Aggregation'
export * from './AggregationsInner'
export * from './AggregationsInnerAllOfAggregationsInner'
export * from './Characteristic'
export * from './Competence'
export * from './CompetenceLevel'
export * from './CompetenceLevelDescriptiveStatistics'
export * from './CompetenceLevelDescriptiveStatisticsDescriptiveStatistics'
export * from './CompetenceLevelStatisticsInner'
export * from './CompetenceLevelsInner'
export * from './DescriptiveStatistics'
export * from './DescriptiveStatisticsDescriptiveStatistics'
export * from './Domain'
export * from './Exercise'
export * from './GenderCharacteristic'
export * from './Item'
export * from './ItemParameters'
export * from './ItemStatisticsInner'
export * from './ItemsInner'
export * from './LanguageAtHomeCharacteristic'
export * from './OtherCharacteristic'
export * from './Subject'
export * from './ValueGroup'
export * from './ValueGroupPropertiesInner'
