/* tslint:disable */
/* eslint-disable */
/**
 * TBA III
 * Diese API ermöglicht den Zugriff auf Auswertungsdaten von VERA. Sie bietet Endpunkte für die Abfrage von Leistungsdaten auf verschiedenen Ebenen (Lerngruppe, Schule, Bundesland) und für verschiedene Arten von Daten (Kompetenzstufen, Item-Statistiken, Aggregationen).
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime'
import type { Competence } from './Competence'
import { CompetenceFromJSON, CompetenceFromJSONTyped, CompetenceToJSON, CompetenceToJSONTyped } from './Competence'
import type { CompetenceLevel } from './CompetenceLevel'
import { CompetenceLevelFromJSON, CompetenceLevelFromJSONTyped, CompetenceLevelToJSON, CompetenceLevelToJSONTyped } from './CompetenceLevel'

/**
 * (importierte) Itemparameter aus den Itemkennwerten des IQB. Bisher unvollständige, exemplarische Liste.
 * @export
 * @interface ItemParameters
 */
export interface ItemParameters {
    /**
     * Schwierigkeit des Items in Logit
     * @type {number}
     * @memberof ItemParameters
     */
    logit?: number
    /**
     * Schwierigkeit des Items in Punkten nach deutscher Bildungsstandardmetrik
     * @type {number}
     * @memberof ItemParameters
     */
    bistaPoints?: number
    /**
     * Mittlere Lösungshäufigkeit der Pilotierung an Gymnasien
     * @type {number}
     * @memberof ItemParameters
     */
    solutionFrequencyGymnasium?: number
    /**
     * Mittlere Lösungshäufigkeit der Pilotierung an Nicht-Gymnasien
     * @type {number}
     * @memberof ItemParameters
     */
    solutionFrequencyNonGymnasium?: number
    /**
     * Mittlere Lösungshäufigkeit der Pilotierung an Grundschulen
     * @type {number}
     * @memberof ItemParameters
     */
    solutionFrequencyPrimarySchool?: number
    /**
     * Fach des Items
     * @type {string}
     * @memberof ItemParameters
     */
    subject?: string
    /**
     * Kompetenzbereich des Items
     * @type {string}
     * @memberof ItemParameters
     */
    domain?: string
    /**
     * Kompetenzstufe des Items
     * @type {CompetenceLevel}
     * @memberof ItemParameters
     */
    competenceLevel?: CompetenceLevel
    /**
     * Liste der dem Item zugeordneten Kompetenzen
     * @type {Array<Competence>}
     * @memberof ItemParameters
     */
    competences?: Array<Competence>
}

/**
 * Check if a given object implements the ItemParameters interface.
 */
export function instanceOfItemParameters(value: object): value is ItemParameters {
    return true
}

export function ItemParametersFromJSON(json: any): ItemParameters {
    return ItemParametersFromJSONTyped(json, false)
}

export function ItemParametersFromJSONTyped(json: any, ignoreDiscriminator: boolean): ItemParameters {
    if (json == null) {
        return json
    }
    return {
        logit: json['logit'] == null ? undefined : json['logit'],
        bistaPoints: json['bistaPoints'] == null ? undefined : json['bistaPoints'],
        solutionFrequencyGymnasium: json['solutionFrequencyGymnasium'] == null ? undefined : json['solutionFrequencyGymnasium'],
        solutionFrequencyNonGymnasium: json['solutionFrequencyNonGymnasium'] == null ? undefined : json['solutionFrequencyNonGymnasium'],
        solutionFrequencyPrimarySchool: json['solutionFrequencyPrimarySchool'] == null ? undefined : json['solutionFrequencyPrimarySchool'],
        subject: json['subject'] == null ? undefined : json['subject'],
        domain: json['domain'] == null ? undefined : json['domain'],
        competenceLevel: json['competenceLevel'] == null ? undefined : CompetenceLevelFromJSON(json['competenceLevel']),
        competences: json['competences'] == null ? undefined : (json['competences'] as Array<any>).map(CompetenceFromJSON),
    }
}

export function ItemParametersToJSON(json: any): ItemParameters {
    return ItemParametersToJSONTyped(json, false)
}

export function ItemParametersToJSONTyped(value?: ItemParameters | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value
    }

    return {
        logit: value['logit'],
        bistaPoints: value['bistaPoints'],
        solutionFrequencyGymnasium: value['solutionFrequencyGymnasium'],
        solutionFrequencyNonGymnasium: value['solutionFrequencyNonGymnasium'],
        solutionFrequencyPrimarySchool: value['solutionFrequencyPrimarySchool'],
        subject: value['subject'],
        domain: value['domain'],
        competenceLevel: CompetenceLevelToJSON(value['competenceLevel']),
        competences: value['competences'] == null ? undefined : (value['competences'] as Array<any>).map(CompetenceToJSON),
    }
}
