/* tslint:disable */
/* eslint-disable */
/**
 * TBA III
 * Diese API ermöglicht den Zugriff auf Auswertungsdaten von VERA. Sie bietet Endpunkte für die Abfrage von Leistungsdaten auf verschiedenen Ebenen (Lerngruppe, Schule, Bundesland) und für verschiedene Arten von Daten (Kompetenzstufen, Item-Statistiken, Aggregationen).
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime'
import type { ValueGroupPropertiesInner } from './ValueGroupPropertiesInner'
import {
    ValueGroupPropertiesInnerFromJSON,
    ValueGroupPropertiesInnerFromJSONTyped,
    ValueGroupPropertiesInnerToJSON,
    ValueGroupPropertiesInnerToJSONTyped,
} from './ValueGroupPropertiesInner'
import type { Characteristic } from './Characteristic'
import { CharacteristicFromJSON, CharacteristicFromJSONTyped, CharacteristicToJSON, CharacteristicToJSONTyped } from './Characteristic'
import type { Domain } from './Domain'
import { DomainFromJSON, DomainFromJSONTyped, DomainToJSON, DomainToJSONTyped } from './Domain'
import type { Subject } from './Subject'
import { SubjectFromJSON, SubjectFromJSONTyped, SubjectToJSON, SubjectToJSONTyped } from './Subject'
import type { ItemStatisticsInner } from './ItemStatisticsInner'
import {
    ItemStatisticsInnerFromJSON,
    ItemStatisticsInnerFromJSONTyped,
    ItemStatisticsInnerToJSON,
    ItemStatisticsInnerToJSONTyped,
} from './ItemStatisticsInner'

/**
 *
 * @export
 * @interface ItemsInner
 */
export interface ItemsInner {
    /**
     *
     * @type {string}
     * @memberof ItemsInner
     */
    id?: string
    /**
     * Bezeichnung der Wertegruppe
     * @type {string}
     * @memberof ItemsInner
     */
    name: string
    /**
     * Domäne der Wertegruppe (optional)
     * @type {Domain}
     * @memberof ItemsInner
     */
    domain?: Domain
    /**
     * Fach der Wertegruppe (optional)
     * @type {Subject}
     * @memberof ItemsInner
     */
    subject?: Subject
    /**
     * Kovariaten der Wertegruppe
     * @type {Array<Characteristic>}
     * @memberof ItemsInner
     */
    covariates?: Array<Characteristic>
    /**
     * Liste von Key-Value-Werten mit zusätzlichen Informationen, z.B. Testdauer, andere systemspezifische Attribute
     * @type {Array<ValueGroupPropertiesInner>}
     * @memberof ItemsInner
     */
    properties?: Array<ValueGroupPropertiesInner>
    /**
     * Statistiken für einzelne Items in der Wertegruppe
     * @type {Array<ItemStatisticsInner>}
     * @memberof ItemsInner
     */
    items: Array<ItemStatisticsInner>
}

/**
 * Check if a given object implements the ItemsInner interface.
 */
export function instanceOfItemsInner(value: object): value is ItemsInner {
    if (!('name' in value) || value['name'] === undefined) return false
    if (!('items' in value) || value['items'] === undefined) return false
    return true
}

export function ItemsInnerFromJSON(json: any): ItemsInner {
    return ItemsInnerFromJSONTyped(json, false)
}

export function ItemsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): ItemsInner {
    if (json == null) {
        return json
    }
    return {
        id: json['id'] == null ? undefined : json['id'],
        name: json['name'],
        domain: json['domain'] == null ? undefined : DomainFromJSON(json['domain']),
        subject: json['subject'] == null ? undefined : SubjectFromJSON(json['subject']),
        covariates: json['covariates'] == null ? undefined : (json['covariates'] as Array<any>).map(CharacteristicFromJSON),
        properties: json['properties'] == null ? undefined : (json['properties'] as Array<any>).map(ValueGroupPropertiesInnerFromJSON),
        items: (json['items'] as Array<any>).map(ItemStatisticsInnerFromJSON),
    }
}

export function ItemsInnerToJSON(json: any): ItemsInner {
    return ItemsInnerToJSONTyped(json, false)
}

export function ItemsInnerToJSONTyped(value?: ItemsInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value
    }

    return {
        id: value['id'],
        name: value['name'],
        domain: DomainToJSON(value['domain']),
        subject: SubjectToJSON(value['subject']),
        covariates: value['covariates'] == null ? undefined : (value['covariates'] as Array<any>).map(CharacteristicToJSON),
        properties: value['properties'] == null ? undefined : (value['properties'] as Array<any>).map(ValueGroupPropertiesInnerToJSON),
        items: (value['items'] as Array<any>).map(ItemStatisticsInnerToJSON),
    }
}
