/* tslint:disable */
/* eslint-disable */
/**
 * TBA III
 * Diese API ermöglicht den Zugriff auf Auswertungsdaten von VERA. Sie bietet Endpunkte für die Abfrage von Leistungsdaten auf verschiedenen Ebenen (Lerngruppe, Schule, Bundesland) und für verschiedene Arten von Daten (Kompetenzstufen, Item-Statistiken, Aggregationen).
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime'
import type { DescriptiveStatisticsDescriptiveStatistics } from './DescriptiveStatisticsDescriptiveStatistics'
import {
    DescriptiveStatisticsDescriptiveStatisticsFromJSON,
    DescriptiveStatisticsDescriptiveStatisticsFromJSONTyped,
    DescriptiveStatisticsDescriptiveStatisticsToJSON,
    DescriptiveStatisticsDescriptiveStatisticsToJSONTyped,
} from './DescriptiveStatisticsDescriptiveStatistics'
import type { ItemParameters } from './ItemParameters'
import { ItemParametersFromJSON, ItemParametersFromJSONTyped, ItemParametersToJSON, ItemParametersToJSONTyped } from './ItemParameters'
import type { Exercise } from './Exercise'
import { ExerciseFromJSON, ExerciseFromJSONTyped, ExerciseToJSON, ExerciseToJSONTyped } from './Exercise'

/**
 *
 * @export
 * @interface ItemStatisticsInner
 */
export interface ItemStatisticsInner {
    /**
     *
     * @type {string}
     * @memberof ItemStatisticsInner
     */
    id?: string
    /**
     * Bezeichnung des Items im Testheft (oft die Fragennummer)
     * @type {string}
     * @memberof ItemStatisticsInner
     */
    name: string
    /**
     * Position des Items im Testheft
     * @type {number}
     * @memberof ItemStatisticsInner
     */
    position?: number
    /**
     * IQB Item-Id des Items
     * @type {string}
     * @memberof ItemStatisticsInner
     */
    iqbId: string
    /**
     * Aufgabe, der das Item zugeordnet ist
     * @type {Exercise}
     * @memberof ItemStatisticsInner
     */
    exercise: Exercise
    /**
     * Itemkennwerte des IQB für das Item
     * @type {ItemParameters}
     * @memberof ItemStatisticsInner
     */
    parameters?: ItemParameters
    /**
     *
     * @type {DescriptiveStatisticsDescriptiveStatistics}
     * @memberof ItemStatisticsInner
     */
    descriptiveStatistics: DescriptiveStatisticsDescriptiveStatistics
}

/**
 * Check if a given object implements the ItemStatisticsInner interface.
 */
export function instanceOfItemStatisticsInner(value: object): value is ItemStatisticsInner {
    if (!('name' in value) || value['name'] === undefined) return false
    if (!('iqbId' in value) || value['iqbId'] === undefined) return false
    if (!('exercise' in value) || value['exercise'] === undefined) return false
    if (!('descriptiveStatistics' in value) || value['descriptiveStatistics'] === undefined) return false
    return true
}

export function ItemStatisticsInnerFromJSON(json: any): ItemStatisticsInner {
    return ItemStatisticsInnerFromJSONTyped(json, false)
}

export function ItemStatisticsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): ItemStatisticsInner {
    if (json == null) {
        return json
    }
    return {
        id: json['id'] == null ? undefined : json['id'],
        name: json['name'],
        position: json['position'] == null ? undefined : json['position'],
        iqbId: json['iqbId'],
        exercise: ExerciseFromJSON(json['exercise']),
        parameters: json['parameters'] == null ? undefined : ItemParametersFromJSON(json['parameters']),
        descriptiveStatistics: DescriptiveStatisticsDescriptiveStatisticsFromJSON(json['descriptiveStatistics']),
    }
}

export function ItemStatisticsInnerToJSON(json: any): ItemStatisticsInner {
    return ItemStatisticsInnerToJSONTyped(json, false)
}

export function ItemStatisticsInnerToJSONTyped(value?: ItemStatisticsInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value
    }

    return {
        id: value['id'],
        name: value['name'],
        position: value['position'],
        iqbId: value['iqbId'],
        exercise: ExerciseToJSON(value['exercise']),
        parameters: ItemParametersToJSON(value['parameters']),
        descriptiveStatistics: DescriptiveStatisticsDescriptiveStatisticsToJSON(value['descriptiveStatistics']),
    }
}
