/* tslint:disable */
/* eslint-disable */
/**
 * TBA III
 * Diese API ermöglicht den Zugriff auf Auswertungsdaten von VERA. Sie bietet Endpunkte für die Abfrage von Leistungsdaten auf verschiedenen Ebenen (Lerngruppe, Schule, Bundesland) und für verschiedene Arten von Daten (Kompetenzstufen, Item-Statistiken, Aggregationen).
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime'
import type { ItemParameters } from './ItemParameters'
import { ItemParametersFromJSON, ItemParametersFromJSONTyped, ItemParametersToJSON, ItemParametersToJSONTyped } from './ItemParameters'
import type { Exercise } from './Exercise'
import { ExerciseFromJSON, ExerciseFromJSONTyped, ExerciseToJSON, ExerciseToJSONTyped } from './Exercise'

/**
 *
 * @export
 * @interface Item
 */
export interface Item {
    /**
     *
     * @type {string}
     * @memberof Item
     */
    id?: string
    /**
     * Bezeichnung des Items im Testheft (oft die Fragennummer)
     * @type {string}
     * @memberof Item
     */
    name: string
    /**
     * Position des Items im Testheft
     * @type {number}
     * @memberof Item
     */
    position?: number
    /**
     * IQB Item-Id des Items
     * @type {string}
     * @memberof Item
     */
    iqbId: string
    /**
     * Aufgabe, der das Item zugeordnet ist
     * @type {Exercise}
     * @memberof Item
     */
    exercise: Exercise
    /**
     * Itemkennwerte des IQB für das Item
     * @type {ItemParameters}
     * @memberof Item
     */
    parameters?: ItemParameters
}

/**
 * Check if a given object implements the Item interface.
 */
export function instanceOfItem(value: object): value is Item {
    if (!('name' in value) || value['name'] === undefined) return false
    if (!('iqbId' in value) || value['iqbId'] === undefined) return false
    if (!('exercise' in value) || value['exercise'] === undefined) return false
    return true
}

export function ItemFromJSON(json: any): Item {
    return ItemFromJSONTyped(json, false)
}

export function ItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): Item {
    if (json == null) {
        return json
    }
    return {
        id: json['id'] == null ? undefined : json['id'],
        name: json['name'],
        position: json['position'] == null ? undefined : json['position'],
        iqbId: json['iqbId'],
        exercise: ExerciseFromJSON(json['exercise']),
        parameters: json['parameters'] == null ? undefined : ItemParametersFromJSON(json['parameters']),
    }
}

export function ItemToJSON(json: any): Item {
    return ItemToJSONTyped(json, false)
}

export function ItemToJSONTyped(value?: Item | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value
    }

    return {
        id: value['id'],
        name: value['name'],
        position: value['position'],
        iqbId: value['iqbId'],
        exercise: ExerciseToJSON(value['exercise']),
        parameters: ItemParametersToJSON(value['parameters']),
    }
}
