/* tslint:disable */
/* eslint-disable */
/**
 * TBA III
 * Diese API ermöglicht den Zugriff auf Auswertungsdaten von VERA. Sie bietet Endpunkte für die Abfrage von Leistungsdaten auf verschiedenen Ebenen (Lerngruppe, Schule, Bundesland) und für verschiedene Arten von Daten (Kompetenzstufen, Item-Statistiken, Aggregationen).
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime'
/**
 *
 * @export
 * @interface LanguageAtHomeCharacteristic
 */
export interface LanguageAtHomeCharacteristic {
    /**
     * Type of characteristic
     * @type {LanguageAtHomeCharacteristicTypeEnum}
     * @memberof LanguageAtHomeCharacteristic
     */
    type: LanguageAtHomeCharacteristicTypeEnum
    /**
     * Label for the characteristic
     * @type {string}
     * @memberof LanguageAtHomeCharacteristic
     */
    label?: string
    /**
     * Specific value of the characteristic
     * @type {string}
     * @memberof LanguageAtHomeCharacteristic
     */
    value: string
}

/**
 * @export
 */
export const LanguageAtHomeCharacteristicTypeEnum = {
    LanguageAtHome: 'languageAtHome',
} as const
export type LanguageAtHomeCharacteristicTypeEnum =
    (typeof LanguageAtHomeCharacteristicTypeEnum)[keyof typeof LanguageAtHomeCharacteristicTypeEnum]

/**
 * Check if a given object implements the LanguageAtHomeCharacteristic interface.
 */
export function instanceOfLanguageAtHomeCharacteristic(value: object): value is LanguageAtHomeCharacteristic {
    if (!('type' in value) || value['type'] === undefined) return false
    if (!('value' in value) || value['value'] === undefined) return false
    return true
}

export function LanguageAtHomeCharacteristicFromJSON(json: any): LanguageAtHomeCharacteristic {
    return LanguageAtHomeCharacteristicFromJSONTyped(json, false)
}

export function LanguageAtHomeCharacteristicFromJSONTyped(json: any, ignoreDiscriminator: boolean): LanguageAtHomeCharacteristic {
    if (json == null) {
        return json
    }
    return {
        type: json['type'],
        label: json['label'] == null ? undefined : json['label'],
        value: json['value'],
    }
}

export function LanguageAtHomeCharacteristicToJSON(json: any): LanguageAtHomeCharacteristic {
    return LanguageAtHomeCharacteristicToJSONTyped(json, false)
}

export function LanguageAtHomeCharacteristicToJSONTyped(
    value?: LanguageAtHomeCharacteristic | null,
    ignoreDiscriminator: boolean = false,
): any {
    if (value == null) {
        return value
    }

    return {
        type: value['type'],
        label: value['label'],
        value: value['value'],
    }
}
