/* tslint:disable */
/* eslint-disable */
/**
 * TBA III
 * Diese API ermöglicht den Zugriff auf Auswertungsdaten von VERA. Sie bietet Endpunkte für die Abfrage von Leistungsdaten auf verschiedenen Ebenen (Lerngruppe, Schule, Bundesland) und für verschiedene Arten von Daten (Kompetenzstufen, Item-Statistiken, Aggregationen).
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime'
/**
 *
 * @export
 * @interface OtherCharacteristic
 */
export interface OtherCharacteristic {
    /**
     * Type of characteristic (fallback for any other type)
     * @type {string}
     * @memberof OtherCharacteristic
     */
    type: string
    /**
     * Label for the characteristic
     * @type {string}
     * @memberof OtherCharacteristic
     */
    label?: string
    /**
     * Specific value of the characteristic
     * @type {string}
     * @memberof OtherCharacteristic
     */
    value: string
}

/**
 * Check if a given object implements the OtherCharacteristic interface.
 */
export function instanceOfOtherCharacteristic(value: object): value is OtherCharacteristic {
    if (!('type' in value) || value['type'] === undefined) return false
    if (!('value' in value) || value['value'] === undefined) return false
    return true
}

export function OtherCharacteristicFromJSON(json: any): OtherCharacteristic {
    return OtherCharacteristicFromJSONTyped(json, false)
}

export function OtherCharacteristicFromJSONTyped(json: any, ignoreDiscriminator: boolean): OtherCharacteristic {
    if (json == null) {
        return json
    }
    return {
        type: json['type'],
        label: json['label'] == null ? undefined : json['label'],
        value: json['value'],
    }
}

export function OtherCharacteristicToJSON(json: any): OtherCharacteristic {
    return OtherCharacteristicToJSONTyped(json, false)
}

export function OtherCharacteristicToJSONTyped(value?: OtherCharacteristic | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value
    }

    return {
        type: value['type'],
        label: value['label'],
        value: value['value'],
    }
}
