/* tslint:disable */
/* eslint-disable */
/**
 * TBA III
 * Diese API ermöglicht den Zugriff auf Auswertungsdaten von VERA. Sie bietet Endpunkte für die Abfrage von Leistungsdaten auf verschiedenen Ebenen (Lerngruppe, Schule, Bundesland) und für verschiedene Arten von Daten (Kompetenzstufen, Item-Statistiken, Aggregationen).
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime'
/**
 *
 * @export
 * @interface Subject
 */
export interface Subject {
    /**
     *
     * @type {string}
     * @memberof Subject
     */
    id?: string
    /**
     * Name des Fachs
     * @type {string}
     * @memberof Subject
     */
    name: string
}

/**
 * Check if a given object implements the Subject interface.
 */
export function instanceOfSubject(value: object): value is Subject {
    if (!('name' in value) || value['name'] === undefined) return false
    return true
}

export function SubjectFromJSON(json: any): Subject {
    return SubjectFromJSONTyped(json, false)
}

export function SubjectFromJSONTyped(json: any, ignoreDiscriminator: boolean): Subject {
    if (json == null) {
        return json
    }
    return {
        id: json['id'] == null ? undefined : json['id'],
        name: json['name'],
    }
}

export function SubjectToJSON(json: any): Subject {
    return SubjectToJSONTyped(json, false)
}

export function SubjectToJSONTyped(value?: Subject | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value
    }

    return {
        id: value['id'],
        name: value['name'],
    }
}
