/* tslint:disable */
/* eslint-disable */
/**
 * TBA III
 * Diese API ermöglicht den Zugriff auf Auswertungsdaten von VERA. Sie bietet Endpunkte für die Abfrage von Leistungsdaten auf verschiedenen Ebenen (Lerngruppe, Schule, Bundesland) und für verschiedene Arten von Daten (Kompetenzstufen, Item-Statistiken, Aggregationen).
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime'
import type { ValueGroupPropertiesInner } from './ValueGroupPropertiesInner'
import {
    ValueGroupPropertiesInnerFromJSON,
    ValueGroupPropertiesInnerFromJSONTyped,
    ValueGroupPropertiesInnerToJSON,
    ValueGroupPropertiesInnerToJSONTyped,
} from './ValueGroupPropertiesInner'
import type { Characteristic } from './Characteristic'
import { CharacteristicFromJSON, CharacteristicFromJSONTyped, CharacteristicToJSON, CharacteristicToJSONTyped } from './Characteristic'
import type { Domain } from './Domain'
import { DomainFromJSON, DomainFromJSONTyped, DomainToJSON, DomainToJSONTyped } from './Domain'
import type { Subject } from './Subject'
import { SubjectFromJSON, SubjectFromJSONTyped, SubjectToJSON, SubjectToJSONTyped } from './Subject'

/**
 *
 * @export
 * @interface ValueGroup
 */
export interface ValueGroup {
    /**
     *
     * @type {string}
     * @memberof ValueGroup
     */
    id?: string
    /**
     * Bezeichnung der Wertegruppe
     * @type {string}
     * @memberof ValueGroup
     */
    name: string
    /**
     * Domäne der Wertegruppe (optional)
     * @type {Domain}
     * @memberof ValueGroup
     */
    domain?: Domain
    /**
     * Fach der Wertegruppe (optional)
     * @type {Subject}
     * @memberof ValueGroup
     */
    subject?: Subject
    /**
     * Kovariaten der Wertegruppe
     * @type {Array<Characteristic>}
     * @memberof ValueGroup
     */
    covariates?: Array<Characteristic>
    /**
     * Liste von Key-Value-Werten mit zusätzlichen Informationen, z.B. Testdauer, andere systemspezifische Attribute
     * @type {Array<ValueGroupPropertiesInner>}
     * @memberof ValueGroup
     */
    properties?: Array<ValueGroupPropertiesInner>
}

/**
 * Check if a given object implements the ValueGroup interface.
 */
export function instanceOfValueGroup(value: object): value is ValueGroup {
    if (!('name' in value) || value['name'] === undefined) return false
    return true
}

export function ValueGroupFromJSON(json: any): ValueGroup {
    return ValueGroupFromJSONTyped(json, false)
}

export function ValueGroupFromJSONTyped(json: any, ignoreDiscriminator: boolean): ValueGroup {
    if (json == null) {
        return json
    }
    return {
        id: json['id'] == null ? undefined : json['id'],
        name: json['name'],
        domain: json['domain'] == null ? undefined : DomainFromJSON(json['domain']),
        subject: json['subject'] == null ? undefined : SubjectFromJSON(json['subject']),
        covariates: json['covariates'] == null ? undefined : (json['covariates'] as Array<any>).map(CharacteristicFromJSON),
        properties: json['properties'] == null ? undefined : (json['properties'] as Array<any>).map(ValueGroupPropertiesInnerFromJSON),
    }
}

export function ValueGroupToJSON(json: any): ValueGroup {
    return ValueGroupToJSONTyped(json, false)
}

export function ValueGroupToJSONTyped(value?: ValueGroup | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value
    }

    return {
        id: value['id'],
        name: value['name'],
        domain: DomainToJSON(value['domain']),
        subject: SubjectToJSON(value['subject']),
        covariates: value['covariates'] == null ? undefined : (value['covariates'] as Array<any>).map(CharacteristicToJSON),
        properties: value['properties'] == null ? undefined : (value['properties'] as Array<any>).map(ValueGroupPropertiesInnerToJSON),
    }
}
