/* tslint:disable */
/* eslint-disable */
/**
 * TBA III
 * Diese API ermöglicht den Zugriff auf Auswertungsdaten von VERA. Sie bietet Endpunkte für die Abfrage von Leistungsdaten auf verschiedenen Ebenen (Lerngruppe, Schule, Bundesland) und für verschiedene Arten von Daten (Kompetenzstufen, Item-Statistiken, Aggregationen).
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime'
/**
 *
 * @export
 * @interface ValueGroupPropertiesInner
 */
export interface ValueGroupPropertiesInner {
    /**
     *
     * @type {string}
     * @memberof ValueGroupPropertiesInner
     */
    key: string
    /**
     *
     * @type {string}
     * @memberof ValueGroupPropertiesInner
     */
    value: string
}

/**
 * Check if a given object implements the ValueGroupPropertiesInner interface.
 */
export function instanceOfValueGroupPropertiesInner(value: object): value is ValueGroupPropertiesInner {
    if (!('key' in value) || value['key'] === undefined) return false
    if (!('value' in value) || value['value'] === undefined) return false
    return true
}

export function ValueGroupPropertiesInnerFromJSON(json: any): ValueGroupPropertiesInner {
    return ValueGroupPropertiesInnerFromJSONTyped(json, false)
}

export function ValueGroupPropertiesInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): ValueGroupPropertiesInner {
    if (json == null) {
        return json
    }
    return {
        key: json['key'],
        value: json['value'],
    }
}

export function ValueGroupPropertiesInnerToJSON(json: any): ValueGroupPropertiesInner {
    return ValueGroupPropertiesInnerToJSONTyped(json, false)
}

export function ValueGroupPropertiesInnerToJSONTyped(value?: ValueGroupPropertiesInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value
    }

    return {
        key: value['key'],
        value: value['value'],
    }
}
